Initial implementation
CoreumFoundation/faucet pull request #1
Opened 2022-08-08 13:31 UTC by miladz68

The initial implementation of the faucet. It works with a single private key and is not concurrent safe.

2022-08-08 13:39 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`main.go` line 89 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xfZBM4yGhiHCU25Oq:-N8xfZBM4yGhiHCU25Or:b-acsjs5) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L89)):*
> ```Go
> 	transferAmount := flagSet.Int64(flagTransferAmount, 1000000, "how much to transfer in each request")
> 	keyFile := flagSet.String(flagPrivKeyFile, "private_keys_unarmored_hex.txt", "path to file containing hex encoded unarmored private keys, each line must contain one private key")
> 	//nolint:errcheck // since we have set ExitOnError on flagset, we don't need to check for errors here
> ```

nolint exception there could be replaced by `_`

Like this:

```
_ = flagSet.Parse(os.Args[1:])
```


<!-- Sent from Reviewable.io -->

2022-08-08 13:41 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`main.go` line 103 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xfipM9JzOzjy-Qze9:-N8xfipM9JzOzjy-QzeA:bb7m3zj) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L103)):*
> ```Go
> 	file, err := os.Open(path)
> 	if err != nil {
> 		return nil, errors.Wrapf(err, "unable to ope file at %s", path)
> ```

opeN
___
*[`client/coreum/coreum.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xg4vB2IvEQ7S5KtLt:-N8xg4vCA0Kzj15jWAPq:b-i975wp) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/client/coreum/coreum.go#L41)):*
> ```Go
> 	sourcePrivateKey types.Secp256k1PrivateKey,
> 	amount types.Coin,
> 	destAddress sdk.AccAddress,
> ```

🚨🚨🚨🚨🚨
sdk type leakage!


<!-- Sent from Reviewable.io -->

2022-08-08 13:44 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`http/http.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xgj-K3sQFqGCfS6ZS:-N8xgj-K3sQFqGCfS6ZT:bv9vog7) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L50)):*
> ```Go
> 	err := parseJSONReqBody(req, &rqBody)
> 	if err != nil {
> 		fmt.Println("err read body", err)
> ```

should be logger, not fmt


<!-- Sent from Reviewable.io -->

2022-08-08 13:45 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`http/http.go` line 70 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xguUx2NBXDtSPw8a3:-N8xguUyB_izuMVVhr0m:beakvwx) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L70)):*
> ```Go
> 	decoder := json.NewDecoder(req.Body)
> 	defer req.Body.Close()
> 	return decoder.Decode(i)
> ```

What if send 120GB JSON there?


<!-- Sent from Reviewable.io -->

2022-08-08 13:45 UTC, xlab reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 0 of 9 files reviewed, 6 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, and @ysv)

___
*[`http/http.go` line 78 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xh1eS3isNVV2tAqTO:-N8xh1eS3isNVV2tAqTP:b6dzttc) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L78)):*
> ```Go
> 	encode := json.NewEncoder(resp)
> 	if err := encode.Encode(msg); err != nil {
> 	}
> ```

missing err handler


<!-- Sent from Reviewable.io -->

2022-08-08 15:27 UTC, wojtek-coreum reviewed
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 30 unresolved discussions (waiting on @miladz68, @oliverasistemas, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xwdxV75kFvDnPGill:-N8xwdxV75kFvDnPGilm:b-m1nscq) (no related file):*
I have a feeling that introducing separate layers and packages for app and http is an overengineering here. The functionality here is so simple that entire business logic could be done inside a single function. Let's discuss it tomorrow.

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xyXZX9l8_3mn3W8SH:-N8xyXZY1rZ1fX7UceFA:bt7oh3u) (no related file):*
Also have some general non-blocking question. Would you prefer to start building some generic foundation here, common to all our future http services or just take the shortest path? By foundation I mean sth that:
- provides common way to start and gracefully shutdown the service once ctx is cancelled
- to support a generic way of adding middleware to the http request, here logger is a bit hardcoded
- handling function which makes it possible to return an error (to be logged) rtaher than log it manually every time
- assigning random ID to each incoming request
- etc

Sooner or later we will have to do it anyway because it would be a nonsense to implement it from scratch in every app

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8y3CIE8YOpXVPzrWet:-N8y3CIF6Znv2TbSkJQT:b-5e7crh) (no related file):*
Please paste here an encoded private key I could take to test running the faucet

___
___
*[`main.go` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xuWmx3QrAZ9CiQKeW:-N8xuWmyAw7-tncjyoZ8:b-fbvoff) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L7)):*
> ```Go
> 	"context"
> 	"encoding/hex"
> 	"flag"
> ```

Let's use github.com/spf13/pflag everywhere. it's much better package, copatible with the standard one.
___
*[`main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xte6qBmmyXTUP8VKc:-N8xte6r5ri4N2kZK3Q4:bj1neqj) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L32)):*
> ```Go
> )
> 
> func main() {
> ```

There are few general things going on here:
- signals are not handled
- logger is configured differently than in crust, znet and contracts
- everything is done manually

I highly recommend to not reinvent the wheel in every application and do repeatable tasks once.
`run.Service` is there, ready to reuse://github.com/CoreumFoundation/coreum-tools/blob/master/pkg/run/run.go#L27 which gives you:
- ctx
- logger configured in unified way, ready to use context and
- signal handler
- logging for error returned by app
___
*[`main.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xu2Mh0zCwwy9W-rih:-N8xu2Mh0zCwwy9W-rii:by7b439) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L41)):*
> ```Go
> 	if err != nil {
> 		log.Fatal(
> 			"unable to get network config for chain-id",
> ```

Here and everywhere: Please start logs with capital letter
___
*[`main.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xu85m16jWKSaqNUBx:-N8xu85n9pt-GjdCUV7z:bkijptz) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L47)):*
> ```Go
> 	}
> 
> 	network.SetupPrefixes()
> ```

Please let's do it correctly and implement our own address encoder. The number of places where this hack is used only grows.
___
*[`main.go` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xviOM1CR5-IjbvQ-7:-N8xviOM1CR5-IjbvQ-8:b-y7jjoa) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L67)):*
> ```Go
> 	app := app.New(cl, network, transferAmount, privateKeys[0])
> 	server := http.New(app)
> 	err = server.ListenAndServe(ctx, config.port)
> ```

Once signals are handled you need to shutdown server gracefully when `ctx` is canceled.
In previous company we wrote our wrapper around http server to implement all those repeatable tasks (like shutdown, adding logger to request's context etc.) once. We don't need to do similar thing here, but it will be useful in the future anyway. A minimal thing to do here is to shutdown the service gracefully.
___
*[`main.go` line 86 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xwHoY0yg-NdJO93C9:-N8xwHoY0yg-NdJO93CA:buisgz1) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L86)):*
> ```Go
> 	chainID := flagSet.String(flagChainID, string(coreumApp.DefaultChainID), "The network chain ID")
> 	node := flagSet.String(flagNode, "localhost:26657", "<host>:<port> to Tendermint RPC interface for this chain")
> 	port := flagSet.Int(flagPort, 8090, "port to start listening for http requests")
> ```

instead of port, it should take full address <host>:<port>. It's not good if you can't limit the service to listen only on single IP.
___
*[`main.go` line 105 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xrbCz5Hhdu3tJn8c9:-N8xrbCz5Hhdu3tJn8cA:b-13p0vq) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L105)):*
> ```Go
> 		return nil, errors.Wrapf(err, "unable to ope file at %s", path)
> 	}
> 	scanner := bufio.NewScanner(file)
> ```

missing `defer file.Close()`
___
*[`main.go` line 108 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xrq67-oj4iSZohwpu:-N8xrq67-oj4iSZohwpv:b-wf5ldk) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L108)):*
> ```Go
> 	var list []types.Secp256k1PrivateKey
> 	for scanner.Scan() {
> 		prvKey, err := hex.DecodeString(scanner.Text())
> ```

prvKey -> privKey

Not very important but it really makes it easier to read if vowels are preserved
___
*[`app/app.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xx-qw2BkmyIPv0BKp:-N8xx-qw2BkmyIPv0BKq:b9gvgt3) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/app.go#L15)):*
> ```Go
> // App implements core functionality
> type App struct {
> 	FundsPrivateKey types.Secp256k1PrivateKey
> ```

Unexport `FundsPrivateKey`?
___
*[`app/parse_addr.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xqn0iEIEqTWRXmr3C:-N8xqn0iEIEqTWRXmr3D:bu6smba) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/parse_addr.go#L12)):*
> ```Go
> 
> func parseAddress(address string) (string, sdk.AccAddress, error) {
> 	if len(strings.TrimSpace(address)) == 0 {
> ```

I see you also use `len` for checking if string is empty or not. Is it any type of convention to do it this way instead of `== ""`?
___
*[`app/parse_addr.go` line 18 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xqVvp4PyB1H7y321T:-N8xqVvp4PyB1H7y321U:b-4z68vv) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/parse_addr.go#L18)):*
> ```Go
> 	hrp, bz, err := bech32.DecodeAndConvert(address)
> 	if err != nil {
> 		return "", nil, err
> ```

add `errors.WithStack`
___
*[`app/parse_addr.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xqZh2EBJEoyB-bX1E:-N8xqZh35MDV5uV5imJ8:b-4z68vv) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/parse_addr.go#L23)):*
> ```Go
> 	err = sdk.VerifyAddressFormat(bz)
> 	if err != nil {
> 		return "", nil, err
> ```

add `errors.WithStack`
___
*[`client/coreum/coreum.go` line 47 at r1](https://reviewable.io/revi [...]

2022-08-08 15:48 UTC, xlab commented
*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8y3CIE8YOpXVPzrWet:-N8y85dfEvrMpXBC-6Qs:b-jqwylu) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please paste here an encoded private key I could take to test running the faucet
</blockquote></details>

:) and also publish the method of PK generation since cored can provide only keyring-stored keys.




<!-- Sent from Reviewable.io -->

2022-08-08 15:50 UTC, xlab commented
*[`app/parse_addr.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xqn0iEIEqTWRXmr3C:-N8y8Tpo8WBFBGmTqSPu:b8njnfb) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/parse_addr.go#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I see you also use `len` for checking if string is empty or not. Is it any type of convention to do it this way instead of `== ""`?
</blockquote></details>

It sounds natural when you read it loud. Also, the subject string can be replaced with `[]byte`. String is a sequence of bytes, so the types shall be replaceable without changing code around it.


<!-- Sent from Reviewable.io -->

2022-08-09 07:40 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 30 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8y3CIE8YOpXVPzrWet:-N90XIs47D28l46c6WGl:b-guqfx5) (no related file):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

:) and also publish the method of PK generation since cored can provide only keyring-stored keys.
</blockquote></details>

@wojtek-coreum @xlab 
here is one of the keys we use in znet
```
9bc9d0151102940992fd2badbe36631fed30100d6e24b1c258b4fde4afddf240
```  
@xlab 
regarding the key generation method. I did this one programatically, but the method is to use this command
```
cored keys export <keyname> --chain-id=coreum-devnet-1 --keyring-backend test --unsafe --unarmored-hex
```

___


<!-- Sent from Reviewable.io -->

2022-08-09 07:41 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 30 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xwdxV75kFvDnPGill:-N90XzFR4c4XhquC6GWG:b-knsp7c) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I have a feeling that introducing separate layers and packages for app and http is an overengineering here. The functionality here is so simple that entire business logic could be done inside a single function. Let's discuss it tomorrow.
</blockquote></details>

If you remember, I brought this up in a previous discussion and yaroslav argued that it is better to separate the layers since we don't know if these layers will grow. it also sets a good example on how we layer our service applications.

___


<!-- Sent from Reviewable.io -->

2022-08-09 07:42 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 30 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xyXZX9l8_3mn3W8SH:-N90YLvy8s0_vu25lJl1:b-dw5xjj) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Also have some general non-blocking question. Would you prefer to start building some generic foundation here, common to all our future http services or just take the shortest path? By foundation I mean sth that:
- provides common way to start and gracefully shutdown the service once ctx is cancelled
- to support a generic way of adding middleware to the http request, here logger is a bit hardcoded
- handling function which makes it possible to return an error (to be logged) rtaher than log it manually every time
- assigning random ID to each incoming request
- etc

Sooner or later we will have to do it anyway because it would be a nonsense to implement it from scratch in every app
</blockquote></details>

let's discuss these in quick call

___


<!-- Sent from Reviewable.io -->

2022-08-09 08:06 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 30 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xwdxV75kFvDnPGill:-N90cm7K974lIx5rk6Mg:b-zfy7b) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

If you remember, I brought this up in a previous discussion and yaroslav argued that it is better to separate the layers since we don't know if these layers will grow. it also sets a good example on how we layer our service applications.
</blockquote></details>

yes, I remember but the functionality here is so trivial that my brain is turned inside out when I see those layers here.

@ysv WDYT?

___


<!-- Sent from Reviewable.io -->

2022-08-09 13:00 UTC, oliverasistemas reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 31 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/parse_addr.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N91g5W2DIj1deroFNWg:-N91g5W2DIj1deroFNWh:b-vliaru) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/parse_addr.go#L26)):*
> ```Go
> 	}
> 
> 	return hrp, sdk.AccAddress(bz), nil
> ```

I believe the type conversion is redundant. Type `sdk.Accress` is a byte array, same as `bz` variable.


<!-- Sent from Reviewable.io -->

2022-08-09 13:01 UTC, oliverasistemas reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 31 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/parse_addr.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N91g5W2DIj1deroFNWg:-N91gWt9DxfugQNEudqA:b-uz5dy6) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/parse_addr.go#L26)):*
<details><summary><i>Previously, oliverasistemas (Adolfo Olivera) wrote…</i></summary><blockquote>

I believe the type conversion is redundant. Type `sdk.Accress` is a byte array, same as `bz` variable.
</blockquote></details>

(*) `sdk.address`


<!-- Sent from Reviewable.io -->

2022-08-09 13:08 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 4 of 11 files reviewed, 31 unresolved discussions (waiting on @miladz68, @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xuWmx3QrAZ9CiQKeW:-N90ZmTsAriaHUEMvfCA:b-cgkgw2) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L7)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Let's use github.com/spf13/pflag everywhere. it's much better package, copatible with the standard one.
</blockquote></details>

Done.
But I wonder what makes it a better package ?
___
*[`main.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xu2Mh0zCwwy9W-rih:-N90lJ_Y0tnIWv0lUyHA:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L41)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Here and everywhere: Please start logs with capital letter
</blockquote></details>

Done.
___
*[`main.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xu85m16jWKSaqNUBx:-N90lNsC5c7c5qSopAvE:bvdlohu) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Please let's do it correctly and implement our own address encoder. The number of places where this hack is used only grows.
</blockquote></details>

refactoring this is easy, once that method is removed, the compiler will complaing and we will adjust. This is not a big issue IMO.
___
*[`main.go` line 67 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xviOM1CR5-IjbvQ-7:-N91g98H2YhrHT_tiafg:b-qivxn1) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L67)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Once signals are handled you need to shutdown server gracefully when `ctx` is canceled.
In previous company we wrote our wrapper around http server to implement all those repeatable tasks (like shutdown, adding logger to request's context etc.) once. We don't need to do similar thing here, but it will be useful in the future anyway. A minimal thing to do here is to shutdown the service gracefully.
</blockquote></details>

I handled the graceful shut down here, but not generically. 
___
*[`main.go` line 86 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xwHoY0yg-NdJO93C9:-N90o7YkAGmjN1N3GKUc:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L86)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

instead of port, it should take full address <host>:<port>. It's not good if you can't limit the service to listen only on single IP.
</blockquote></details>

Done.
___
*[`main.go` line 89 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xfZBM4yGhiHCU25Oq:-N90oDZI-dAf1vBRHHGJ:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L89)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

nolint exception there could be replaced by `_`

Like this:

```
_ = flagSet.Parse(os.Args[1:])
```
</blockquote></details>

Done.
___
*[`main.go` line 103 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xfipM9JzOzjy-Qze9:-N90oF-8Dlo4APpqpArD:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L103)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

opeN
</blockquote></details>

Done.
___
*[`main.go` line 105 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xrbCz5Hhdu3tJn8c9:-N90oPCFEGk8Y_HCWK8z:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L105)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

missing `defer file.Close()`
</blockquote></details>

Done.
___
*[`main.go` line 108 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xrq67-oj4iSZohwpu:-N90oRFN-oubg0PNBVTi:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L108)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

prvKey -> privKey

Not very important but it really makes it easier to read if vowels are preserved
</blockquote></details>

Done.
___
*[`app/app.go` line 15 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xx-qw2BkmyIPv0BKp:-N90o_aHA9ixBFPQd7Cb:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/app.go#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Unexport `FundsPrivateKey`?
</blockquote></details>

Done.
___
*[`app/parse_addr.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xqn0iEIEqTWRXmr3C:-N90onVI4uYHCh2BboJG:baef0li) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/parse_addr.go#L12)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

It sounds natural when you read it loud. Also, the subject string can be replaced with `[]byte`. String is a sequence of bytes, so the types shall be replaceable without changing code around it.
</blockquote></details>

not a convention, but this check looks the same for maps,lists, strings and bytes, So kinda easier to read and write. 
___
*[`app/parse_addr.go` line 18 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xqVvp4PyB1H7y321T:-N90pY_EAUBH1TE_Tekx:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/parse_addr.go#L18)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

add `errors.WithStack`
</blockquote></details>

Done.
___
*[`app/parse_addr.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xqZh2EBJEoyB-bX1E:-N90pZ3g7FofxZV1PmQA:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/parse_addr.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

add `errors.WithStack`
</blockquote></details>

Done.
___
*[`app/parse_addr.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N91g5W2DIj1deroFNWg:-N91hfKkCNnAgUqIaJjt:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/parse_addr.go#L26)):*
<details><summary><i>Previously, oliverasistemas (Adolfo Olivera) wrote…</i></summary><blockquote>

(*) `sdk.address`
</blockquote></details>

Done.
___
*[`client/coreum/coreum.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xg4vB2IvEQ7S5KtLt:-N90pk1K7gBdmURraVoL:b64f654) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/client/coreum/coreum.go#L41)):*
<details><summary><i>Previously, xlab (Max Kupriianov) wrote…</i></summary><blockquote>

🚨🚨🚨🚨🚨
sdk type leakage!
</blockquote></details>

We need to define a better abstraction in cosmos client to avoid this leakage. Currently the implementation will not work  without this leak.
___
*[`http/http.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xgj-K3sQFqGCfS6ZS:-N90qE6c6EARN-SP9vhr:b-mpqi8y) ([raw file](https://githu [...]

2022-08-09 13:11 UTC, oliverasistemas reviewed
> Reviewed 3 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 7 of 11 files reviewed, 30 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-09 13:39 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 7 of 11 files reviewed, 21 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`app/parse_addr.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xqn0iEIEqTWRXmr3C:-N91o3fA5Lrbka-lupWC:b7417ko) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/parse_addr.go#L12)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

not a convention, but this check looks the same for maps,lists, strings and bytes, So kinda easier to read and write. 
</blockquote></details>

@ysv WDYT?
___
*[`http/http.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xzLV22_ydbGi9Ht01:-N91oFT_9TsnVr0BxBqs:b-f7wdsx) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L50)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it is actually a left over code. removed.
</blockquote></details>

But actually, errors happening inside handler should be logged, not silently ignored
___
*[`http/http.go` line 111 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N91oX5b0zA6_PpmfpKP:-N91oX5b0zA6_PpmfpKQ:bae8hfa) ([raw file](https://github.com/coreumfoundation/faucet/blob/1a2f3524cae855b61f16d5a0553dcbff332cf111/http/http.go#L111)):*
> ```Go
> 		return errors.WithStack(err)
> 	}
> 	err = json.Unmarshal(body, i)
> ```

You may do `return errors.WithStack(json.Unmarshal(...))`


<!-- Sent from Reviewable.io -->

2022-08-10 06:23 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 6 of 11 files reviewed, 21 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xte6qBmmyXTUP8VKc:-N95HpWF0ERahpT1jUTO:b-5kxn28) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

There are few general things going on here:
- signals are not handled
- logger is configured differently than in crust, znet and contracts
- everything is done manually

I highly recommend to not reinvent the wheel in every application and do repeatable tasks once.
`run.Service` is there, ready to reuse://github.com/CoreumFoundation/coreum-tools/blob/master/pkg/run/run.go#L27 which gives you:
- ctx
- logger configured in unified way, ready to use context and
- signal handler
- logging for error returned by app
</blockquote></details>

- I fixed the way that logger is configured. 
- I am now handling signals and graceful shutdown.
- Regarding the manual operations, I don't the IoC concept introduced in coreum-tools and used in crust. and I think we agreed earlier to move away from that concept. If we want to re discuss using and IoC framework I highly recommend uber/fx and I have recommended before. 
@ysv maybe you would care to comment ?
___
*[`client/coreum/coreum.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xfozs3olO-PsON1BA:-N95Ibv8B_gUk96UYGsO:byyqahm) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/client/coreum/coreum.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You have `c.client.PrepareTxBankSend` for this. I understand that you can't use this at the moment because it takes `Wallet` of receiver (operating on private key) but I would prefer if the client is fixed there in `coreum` first and then used here. We may discuss the better design for that client together because we already have some other use case in WASM which requires it to be done better.
</blockquote></details>

It was decided in call that we will not have an all encompassing client, and the current approach is the way to go.
___
*[`client/coreum/coreum.go` line 55 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xgsZvCYwyayIC9n7w:-N95InZL84y_Bwdz_qGv:bddrc0s) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/client/coreum/coreum.go#L55)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Also here, `tx.BaseInput` there should take private key, instead of wallet probably
</blockquote></details>

I will adjust once the client is done the new way.
___
*[`http/http.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xzLV22_ydbGi9Ht01:-N95K-2m2XfQyVW7iYAr:b-um7xtx) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L50)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But actually, errors happening inside handler should be logged, not silently ignored
</blockquote></details>

I moved the logger to respondErr function
___
*[`http/http.go` line 111 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N91oX5b0zA6_PpmfpKP:-N95KCyU4hYzTTLIp8mj:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/1a2f3524cae855b61f16d5a0553dcbff332cf111/http/http.go#L111)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You may do `return errors.WithStack(json.Unmarshal(...))`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-10 09:57 UTC, wojtek-coreum reviewed
> Reviewed 4 of 7 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 7 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xuWmx3QrAZ9CiQKeW:-N95feLU4QmnMpGf__8X:b-jxalpn) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L7)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
But I wonder what makes it a better package ?
</blockquote></details>

It extends the functionality of `flag` by adding support for:
- shorthands - check `pflag.*P` functions
- supports slices and arrays - check `pflag.StringSLice` for example

Probably it provides other additional features as well, but I don't really know all the differences because I always use `pflag`.

Maybe they are not so important here but we already use `pflag` everywhere (directly or as a part of `cobra`) so it doesn't make much sense to introduce `flag` here.
___
*[`main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xte6qBmmyXTUP8VKc:-N95i2XN4uv1G-zdcqgh:b-93lxkr) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L32)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

- I fixed the way that logger is configured. 
- I am now handling signals and graceful shutdown.
- Regarding the manual operations, I don't the IoC concept introduced in coreum-tools and used in crust. and I think we agreed earlier to move away from that concept. If we want to re discuss using and IoC framework I highly recommend uber/fx and I have recommended before. 
@ysv maybe you would care to comment ?

</blockquote></details>

The target for this comment is entire team, not only you. @ysv please take a look.

I agree that IoC should be removed completely. But also `run.Tool` or `run.Service` does not force people to use IoC. You just pass `nil` like it is done here: https://github.com/CoreumFoundation/crust/blob/f/wasm-contracts/cmd/zstress/main.go#L33

If you are mroe happy if IoC is removed completely from the internals of those functions then let's implement similar functions which does not use IoC at all, reuse them and convert crust to use them as well, and remove existing implementation completely.

The goal is that if we write the same code again it means that:
- it must be written (I don't find anything interesting in writing the same code configuring logger, context and signals again and again)
- it must be reviewed (I don't find anything interesting in reviewing the same code configuring logger, context and signals again and again)
- each instance of this code is another occasion to introduce a bug

We are developers, developing software is about closing common code in functions and reusing it.
___
*[`main.go` line 33 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95jt4U2gOCrGobrWbz:-N95jt4U2gOCrGobrWc-:b-x3btt) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/main.go#L33)):*
> ```Go
> 
> func main() {
> 	log := logger.New(logger.ConfigureWithCLI(logger.Config{Format: "console", Verbose: true}))
> ```

`Format` (and missing support verbosity - '-v` flag) should be taken as CLI arguments. For local operation you want to use console or yaml, but in production you want to use json to send those logs to grafana, elasticsearch or sth else.

Compare:
https://github.com/CoreumFoundation/coreum-tools/blob/master/pkg/logger/config.go#L54
https://github.com/CoreumFoundation/coreum-tools/blob/master/pkg/run/run.go#L46

Related to other comment (https://reviewable.io/reviews/CoreumFoundation/faucet/1#-N8xte6qBmmyXTUP8VKc):
That's why common function delivering all of these is good because we don't need to have this discussion every time new application is introduced.
___
*[`main.go` line 82 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95tT-r3YDao9jSNdJy:-N95tT-r3YDao9jSNdJz:b-v1p63) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/main.go#L82)):*
> ```Go
> 
> func processFlags() config {
> 	flagSet := pflag.NewFlagSet("faucet", pflag.ExitOnError)
> ```

Minor: you don't need to create `flagSet` as long as you don't want to make any magic. `pflag` provides all the functions for creating flags directly.
___
*[`client/coreum/coreum.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xfozs3olO-PsON1BA:-N96A-c575xwdvUgP5ua:b-ezn9zi) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/client/coreum/coreum.go#L47)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

It was decided in call that we will not have an all encompassing client, and the current approach is the way to go.
</blockquote></details>

but probably it must wait for new client
___
*[`http/http.go` line 41 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95u4q0CslXdjJZwQm5:-N95u4q0CslXdjJZwQm6:b-wmwebq) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L41)):*
> ```Go
> 	}
> 
> 	server := http.Server{
> ```

The target for this comment is entire team, not only you. @ysv please take a look.

I would like to also warn everyone that handling all the aspects of http server (websockets, CORS headers, shutdown, logging, passing context to handlers, authentication, assigning IDs to requests, compression) in go is much much more tricky than it seems to be. In previous company we wrote our own wrapper around `http.Server` containing 750 lines of code + unit tests to support all of these. It was long process of discovering pitfalls delivered by default implementation. E.g. Did you know that when you call `Shutdown` method of server to close all connections gracefully, it doesn't close connections opened by websockets ("hijacted" in their terminology), only regular requests?

Having that experience I highly recommend to build generic package serving http services in all the applications we are going to develop. We don't need to add all the aspects I mentioned at once but the sooner we start creating this abstraction the less it will hurt. Trust me, I went through this process.

Sadly speaking, I can't share with you the implementation we made because it's not opensourced.
___
*[`http/http.go` line 46 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95wkNBEwH-fRR9GDBr:-N95wkNBEwH-fRR9GDBs:btnwvbd) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L46)):*
> ```Go
> 	}
> 
> 	exitChan := make(chan error, 1)
> ```

Do you find it exciting to implement this kind of channeling every time in all the software requiring goroutines again, again and again?
Do you like, as a reviewer, to check in every other PR if it is implemented correctly?
___
*[`http/http.go` line 49 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95vfGO2iK9cOzVmC1v:-N95vfGO2iK9cOzVmC1w:bmhf6p3) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L49)):*
> ```Go
> 	go func() {
> 		log.Info("Started listening for http connections", zap.String("address", address))
> 		exitChan <- server.ListenAndServe()
> ```

If `server` panics this code does not give us any information that `faucet` does not serve requests anymore. It silently sits in the memory and does nothing and we are not noticed.

If you think now that "http.Server" is a bullet proven piece of software used by millions of apps in the world, my answer is: Every single piece of code may panic. Panics are always unexpected, if the [...]

2022-08-10 12:21 UTC, ysv reviewed
> Reviewed 2 of 9 files at r1, 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 26 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xwdxV75kFvDnPGill:-N96QHyn12tqN8iKfftD:bxd3wns) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yes, I remember but the functionality here is so trivial that my brain is turned inside out when I see those layers here.

@ysv WDYT?
</blockquote></details>

layers are ok for me
If Milad did more layer I would argue but what we have now is reasonable 

___
*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xyXZX9l8_3mn3W8SH:-N96Qhbu2cnj4GveKBMb:b54xlyx) (no related file):*
> provides common way to start and gracefully shutdown the service once ctx is cancelled
Yes for HTTP services. Generic for everything I'm not sure


> to support a generic way of adding middleware to the http request, here logger is a bit hardcoded
Yes. It is provided by higher level packages like `gorilla/mux`and I don't mind using smth like this


> handling function which makes it possible to return an error (to be logged) rtaher than log it manually every time
This should definitely be done


> assigning random ID to each incoming request
Probably yes

___
___
*[`main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xte6qBmmyXTUP8VKc:-N96TwimA5ECeATF3ojI:bbuo5id) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The target for this comment is entire team, not only you. @ysv please take a look.

I agree that IoC should be removed completely. But also `run.Tool` or `run.Service` does not force people to use IoC. You just pass `nil` like it is done here: https://github.com/CoreumFoundation/crust/blob/f/wasm-contracts/cmd/zstress/main.go#L33

If you are mroe happy if IoC is removed completely from the internals of those functions then let's implement similar functions which does not use IoC at all, reuse them and convert crust to use them as well, and remove existing implementation completely.

The goal is that if we write the same code again it means that:
- it must be written (I don't find anything interesting in writing the same code configuring logger, context and signals again and again)
- it must be reviewed (I don't find anything interesting in reviewing the same code configuring logger, context and signals again and again)
- each instance of this code is another occasion to introduce a bug

We are developers, developing software is about closing common code in functions and reusing it.
</blockquote></details>

run is currently highly tighten with IoC and most of the team doesn't like IoC so we can't use it as it is now.

I briefly inspected `run` and the idea behind probably makes sense. However I still don't see how we can handle graceful HTTP server shutdown there. It should probably be still handle on HTTP server level & implemented separately

@miladz68 I think it is worth taking `run` concept of managing ctx & logger & handling signals etc and adapt it here
___
*[`main.go` line 33 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95jt4U2gOCrGobrWbz:-N96Xkh66MjXvQen57RU:brd7sf8) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/main.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`Format` (and missing support verbosity - '-v` flag) should be taken as CLI arguments. For local operation you want to use console or yaml, but in production you want to use json to send those logs to grafana, elasticsearch or sth else.

Compare:
https://github.com/CoreumFoundation/coreum-tools/blob/master/pkg/logger/config.go#L54
https://github.com/CoreumFoundation/coreum-tools/blob/master/pkg/run/run.go#L46

Related to other comment (https://reviewable.io/reviews/CoreumFoundation/faucet/1#-N8xte6qBmmyXTUP8VKc):
That's why common function delivering all of these is good because we don't need to have this discussion every time new application is introduced.
</blockquote></details>

yes makes sense for me. Ideally it should be done like this
___
*[`app/parse_addr.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xqn0iEIEqTWRXmr3C:-N96Y_SH05HaL0NRGzwz:b-p23i2k) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/parse_addr.go#L12)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@ysv WDYT?
</blockquote></details>

no convention and both ways are ok
Also good points from Maxim

I think it is about preference of eachone

@miladz68 Keep it as you prefer
___
*[`app/parse_addr_test.go` line 37 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N96afj7B58P1NCNC1Qr:-N96afj7B58P1NCNC1Qs:b49a3a) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/app/parse_addr_test.go#L37)):*
> ```Go
> 	}
> 
> 	for i := range testCases {
> ```

minor: 
`for _, tc := range testCases {`

-1 line of code :sweat_smile: 
___
*[`app/parse_addr_test.go` line 39 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N96aY5o3sAA38HYWnER:-N96aY5p58Rtwj70dlPE:bsdhmu) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/app/parse_addr_test.go#L39)):*
> ```Go
> 	for i := range testCases {
> 		tc := testCases[i]
> 		t.Run("", func(t *testing.T) {
> ```

It is better to specify name of test 
Probably just pass address
___
*[`client/coreum/coreum.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xg4vB2IvEQ7S5KtLt:-N96bABl0YzNdcWC-VYq:b-pxbrjb) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/client/coreum/coreum.go#L41)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

We need to define a better abstraction in cosmos client to avoid this leakage. Currently the implementation will not work  without this leak.
</blockquote></details>

discussed yesterday waiting for new client
___
*[`client/coreum/coreum.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xfozs3olO-PsON1BA:-N96bYv_4aIJIMpHSDE1:b-mcw3vz) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/client/coreum/coreum.go#L47)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

but probably it must wait for new client
</blockquote></details>

discussed yesterday waiting for new client
___
*[`http/http.go` line 70 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xguUx2NBXDtSPw8a3:-N96f-lO5cFc32_DOGrN:b989gj) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L70)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I agree that it is better to enforce these policies via the gateway to the application.
</blockquote></details>

yes ingress will limit this
We should not care about all types of http stuff in each svc
___
*[`http/http.go` line 41 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95u4q0CslXdjJZwQm5:-N96bgfdCFmZI5QQF_8p:b-gxttlo) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L41)):*
> (websockets, CORS headers, shutdown, logging, passing context to handlers, authentication, assigning IDs to requests, compression

We should definitely start grouping all of them in pkg/pkgs and add things which are needed one by  [...]

2022-08-10 12:22 UTC, ysv reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 26 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @xlab)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xyXZX9l8_3mn3W8SH:-N96h1Oa1kS3ZPMMyjUz:b3ykhvf) (no related file):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> provides common way to start and gracefully shutdown the service once ctx is cancelled
Yes for HTTP services. Generic for everything I'm not sure


> to support a generic way of adding middleware to the http request, here logger is a bit hardcoded
Yes. It is provided by higher level packages like `gorilla/mux`and I don't mind using smth like this


> handling function which makes it possible to return an error (to be logged) rtaher than log it manually every time
This should definitely be done


> assigning random ID to each incoming request
Probably yes


</blockquote></details>

quote-unquote is sort of broken in a previous comment

___


<!-- Sent from Reviewable.io -->

2022-08-10 13:03 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xte6qBmmyXTUP8VKc:-N96nCyy4Hm0xx_4M1IH:b5her16) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L32)):*
Of course, graceful shutdown must be implemented in http wrapper taking `ctx` and shutting down the http server when it's canceled.

> run is currently highly tighten with IoC and most of the team doesn't like IoC so we can't use it as it is now

I understand and have nothing against removing IoC from there. Let's just do that.
___
*[`http/http.go` line 41 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95u4q0CslXdjJZwQm5:-N96nrRQ59mDKA8AIY9R:b-fklz4k) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L41)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> (websockets, CORS headers, shutdown, logging, passing context to handlers, authentication, assigning IDs to requests, compression

We should definitely start grouping all of them in pkg/pkgs and add things which are needed one by one

What is not needed now:
- CORS (will be handle on ingress level)
- compression (will probably be handle on ingress level)
- websockets (no use-case ofr now)
- authentication (no use-case for now)

Others:
- shutdown (required)
- logging (required)
- passing context (required)
- assigning IDS (opt)

</blockquote></details>

agree, with one exception: generating ID should be required too, it's easy to add and will make our life easier from day-0
___
*[`http/http.go` line 55 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95xrV_1tNpehgWxjlr:-N96oBUJ1m2xTGN2ddnh:b-nmht65) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L55)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but the plan is to move it to a generic pkg and use it everywhere
</blockquote></details>

My comment was not about handling signals (it's just an existing example of code where problem arised). It's about handling parallelism in general. This time I caught this problem here. Another time similar problem with handling parallelism will be found in another case where goroutines are used. I can't give you mathematical proof but I already know that `go` keyword is an evil. It's hard to accept because we use `go` language. But our all problems with deadlocks, unhandled panics etc. went away instantly when we removed all `go` keywords from the applications, except exactly one instance - in library implementing structured concurrency. I understand that it might be tricky to accept that in system having 10s of thousands lines of go code we didn't use `go` keyword, but that's the fact.

Previously when I argued that we need sth like this it was a virtual problem described by me. Now I have a proof that the problem with handling parallelism correctly happened in the first PR ever in this company where someone tried to introduce it using `go` directly. I may bet that those problems will exist in all PRs dealing with this. It means that someone will spend time writing and fixing the code and we will spend time reviewing it.


<!-- Sent from Reviewable.io -->

2022-08-10 13:21 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`http/http.go` line 84 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N962kno3jq1je6e-XSh:-N96u_RK1CiyOAw0yNPm:b-954djt) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L84)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

It is good idea I think

I also have some thoughts on better errors handling will share it directly with Milad
</blockquote></details>

After thinking about more I see that that request ID could be also returned as an HTTP header, not in the body. But solution with body might be easier to use.


<!-- Sent from Reviewable.io -->

2022-08-10 13:41 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 24 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 32 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xte6qBmmyXTUP8VKc:-N96jVKyC85Z7wtNS8Ue:b8kn59y) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Of course, graceful shutdown must be implemented in http wrapper taking `ctx` and shutting down the http server when it's canceled.

> run is currently highly tighten with IoC and most of the team doesn't like IoC so we can't use it as it is now

I understand and have nothing against removing IoC from there. Let's just do that.
</blockquote></details>

I don't like the run approach, since it looks like a framework rather than a library.
It would be better to have an function which returns a logger, shutdown channel (or shutdown ctx), and a flagSet registerer (for common flags like logger flags) and then use them in the main, instead of doing it the other way around and have a run function which runs the application.
Then we can have an http which provides http interface with correct shutdown and middlewares. 
___
*[`main.go` line 33 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95jt4U2gOCrGobrWbz:-N96fiwP0ayVKkZC5YBM:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/main.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`Format` (and missing support verbosity - '-v` flag) should be taken as CLI arguments. For local operation you want to use console or yaml, but in production you want to use json to send those logs to grafana, elasticsearch or sth else.

Compare:
https://github.com/CoreumFoundation/coreum-tools/blob/master/pkg/logger/config.go#L54
https://github.com/CoreumFoundation/coreum-tools/blob/master/pkg/run/run.go#L46

Related to other comment (https://reviewable.io/reviews/CoreumFoundation/faucet/1#-N8xte6qBmmyXTUP8VKc):
That's why common function delivering all of these is good because we don't need to have this discussion every time new application is introduced.
</blockquote></details>

Done.
___
*[`main.go` line 82 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95tT-r3YDao9jSNdJy:-N96fmha5mWSbpS8Qzx6:bp790dw) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/main.go#L82)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Minor: you don't need to create `flagSet` as long as you don't want to make any magic. `pflag` provides all the functions for creating flags directly.
</blockquote></details>

I prefer to have a new instance for flagSet.
___
*[`app/parse_addr.go` line 12 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xqn0iEIEqTWRXmr3C:-N96pDjz7t0kghiu2_nQ:bbtynbp) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/app/parse_addr.go#L12)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

no convention and both ways are ok
Also good points from Maxim

I think it is about preference of eachone

@miladz68 Keep it as you prefer
</blockquote></details>

sounds good, thanks @ysv 
___
*[`app/parse_addr_test.go` line 37 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N96afj7B58P1NCNC1Qr:-N96pItQ2CpVwuV8UmFe:b-gcd6qr) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/app/parse_addr_test.go#L37)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

minor: 
`for _, tc := range testCases {`

-1 line of code :sweat_smile: 
</blockquote></details>

the linter complains that I tc is mutable if I use that
___
*[`app/parse_addr_test.go` line 39 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N96aY5o3sAA38HYWnER:-N96reOF9ZWxmBims5_3:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/app/parse_addr_test.go#L39)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

It is better to specify name of test 
Probably just pass address
</blockquote></details>

Done.
___
*[`http/http.go` line 46 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95wkNBEwH-fRR9GDBr:-N96wxTN63sTaLCQtF6E:b-iy77gn) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L46)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

needs to be moved to a generic pkg
</blockquote></details>

shutdown should be part of the http server package that we write. 
___
*[`http/http.go` line 49 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95vfGO2iK9cOzVmC1v:-N96xFM59B48qsgso_Lw:b-62uptb) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L49)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

needs to be moved to a generic pkg
</blockquote></details>

I argue that we should use a framework instead of inventing our own. Echo, Gin and Fiber are good examples.


<!-- Sent from Reviewable.io -->

2022-08-11 12:28 UTC, wojtek-coreum reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 9 of 11 files reviewed, 24 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 33 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95jt4U2gOCrGobrWbz:-N9BrcSl3Eir-1Q5tUbb:b-c984k8) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/main.go#L33)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It should be `log := logger.New(logger.ConfigureWithCLI(logger.ServiceDefaultConfig)`



_Code quote:_
```Go
log := logger.New(logger.ConfigureWithCLI(logger.Config{Format: "console", Verbose: true}))
```
___
*[`main.go` line 84 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9Brz1H6UwT1TWycH7N:-N9Brz1H6UwT1TWycH7O:b86tpst) ([raw file](https://github.com/coreumfoundation/faucet/blob/6f7e070bb1e52311738d84952a46b612fb079507/main.go#L84)):*
> ```Go
> 	flagSet := pflag.NewFlagSet("faucet", pflag.ExitOnError)
> 
> 	logger.AddFlags(logger.ToolDefaultConfig, flagSet)
> ```

ToolDefaultConfig -> ServiceDefaultConfig

faucet is a service running continuously on server, not tool run by human to do some job


<!-- Sent from Reviewable.io -->

2022-08-15 16:26 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 6 of 18 files reviewed, 23 unresolved discussions (waiting on @oliverasistemas, @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 33 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95jt4U2gOCrGobrWbz:-N9XHjwq0uRNTk0qtcTn:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/main.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It should be `log := logger.New(logger.ConfigureWithCLI(logger.ServiceDefaultConfig)`
</blockquote></details>

Done.
___
*[`main.go` line 84 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9Brz1H6UwT1TWycH7N:-N9XHlVqCeKRZKtAs-C5:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/6f7e070bb1e52311738d84952a46b612fb079507/main.go#L84)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ToolDefaultConfig -> ServiceDefaultConfig

faucet is a service running continuously on server, not tool run by human to do some job
</blockquote></details>

Done.
___
*[`http/http.go` line 70 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xguUx2NBXDtSPw8a3:-N9XJ1vq8Zda9jDfyL-R:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L70)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

yes ingress will limit this
We should not care about all types of http stuff in each svc
</blockquote></details>

Done.
___
*[`http/http.go` line 41 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95u4q0CslXdjJZwQm5:-N9XJxPO7JAgoYYyVsr7:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L41)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

agree, with one exception: generating ID should be required too, it's easy to add and will make our life easier from day-0
</blockquote></details>

Done.
___
*[`http/http.go` line 52 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95wzARC4xj2abIv-wy:-N9XJTxjC4PZ8DN_DMTm:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L52)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

needs to be moved to a generic pkg
</blockquote></details>

Done.
___
*[`http/http.go` line 55 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95xrV_1tNpehgWxjlr:-N9XJWS73mc8c_9RnOr3:b-vttpg) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L55)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

My comment was not about handling signals (it's just an existing example of code where problem arised). It's about handling parallelism in general. This time I caught this problem here. Another time similar problem with handling parallelism will be found in another case where goroutines are used. I can't give you mathematical proof but I already know that `go` keyword is an evil. It's hard to accept because we use `go` language. But our all problems with deadlocks, unhandled panics etc. went away instantly when we removed all `go` keywords from the applications, except exactly one instance - in library implementing structured concurrency. I understand that it might be tricky to accept that in system having 10s of thousands lines of go code we didn't use `go` keyword, but that's the fact.

Previously when I argued that we need sth like this it was a virtual problem described by me. Now I have a proof that the problem with handling parallelism correctly happened in the first PR ever in this company where someone tried to introduce it using `go` directly. I may bet that those problems will exist in all PRs dealing with this. It means that someone will spend time writing and fixing the code and we will spend time reviewing it.
</blockquote></details>

@wojtek-coreum as discussed, this is beyond the scope this PR and we should try out the parallel package and come to the final decision as a team. 
___
*[`http/http.go` line 84 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N962kno3jq1je6e-XSh:-N9XJkgx8NM5a0KJ4mTT:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L84)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

After thinking about more I see that that request ID could be also returned as an HTTP header, not in the body. But solution with body might be easier to use.
</blockquote></details>

Done.
___
*[`http/http.go` line 122 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N963Ihk6hwmvM9ch7_A:-N9XJ6F-1BXwxOmh9287:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/http.go#L122)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Yes 
The idea is to handle domain errors on http level and then initialize/wrap it into HTTP error which contains details provided by domain error + additional info (eg. http status)

Will share details with Milad
</blockquote></details>

Done.
___
*[`http/middleware.go` line 18 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95uf3C6Xx4khS9Qc6N:-N9XJm1YAx0cLXIktSt3:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/middleware.go#L18)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

agree

> returned status code
> ID of the request
should probably go to defer

</blockquote></details>

Done.
___
*[`http/middleware.go` line 27 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N95ukLq3TUZqpHBKNyF:-N9XJn8l2YDYtGMGC2SA:b-bz8w8l) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/http/middleware.go#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

"HTTP request served"

Also please log separately the start and end. Because if handler hangs there will be no evidence that sth is going wrong
</blockquote></details>

remove this code in favor echo built in logger.


<!-- Sent from Reviewable.io -->

2022-08-16 07:26 UTC, wojtek-coreum reviewed
> Reviewed 1 of 2 files at r5, 10 of 11 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 29 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_JMfe96D7G6tTa9-n:-N9_JMfe96D7G6tTa9-o:bupr2e7) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/main.go#L43)):*
> ```Go
> 
> 	ctx := context.Background()
> 	ctx = logger.WithLogger(ctx, log)
> ```

it seems to me that you could add logger to `ctxQuit` and use single context instead of two
___
*[`app/parse_addr_test.go` line 37 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N96afj7B58P1NCNC1Qr:-N9_K-na9UNV3DlsDlO3:b-gpw6z7) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/app/parse_addr_test.go#L37)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the linter complains that I tc is mutable if I use that
</blockquote></details>

eventually `tc := tc`
___
*[`http/errors.go` line 27 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_UcM74Q2XS-5GFzBZ:-N9_UcM74Q2XS-5GFzB_:b-mnqokq) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/http/errors.go#L27)):*
> ```Go
> 				logger = withEchoContext(logger, c)
> 				err := mapError(err)
> 				logger.Error("error processing request", zap.Error(err))
> ```

error -> Error
___
*[`http/errors.go` line 85 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Ut6XCwmVKIMoDSDR:-N9_Ut6XCwmVKIMoDSDS:bkvzy1i) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/http/errors.go#L85)):*
> ```Go
> }
> 
> func mapError(err error) APIError {
> ```

This should not be done like this. HTTP handler should return correct `APIError` directly.
___
*[`pkg/config/config.go` line 19 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_SXX77GHUfrxQNzXu:-N9_SXX77GHUfrxQNzXv:b9azpi7) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/config/config.go#L19)):*
> ```Go
> 	})
> 
> 	for _, fn := range flagNames {
> ```

Couldn't this logic be implemented inside `VisitAll` directly?
___
*[`pkg/config/config.go` line 32 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Sm9F4hKQbQyCnbpO:-N9_Sm9F4hKQbQyCnbpP:b-ecjbn2) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/config/config.go#L32)):*
> ```Go
> 		envValue := os.Getenv(name)
> 		if envValue != "" {
> 			if err = flag.Value.Set(envValue); err != nil {
> ```

you could set default value of the flag, then `--help` will print them correctly and 

```go
		if flag.Changed {
			continue
		}
```

won't be needed
___
*[`pkg/config/config.go` line 33 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_T3de4qnQXZl5fQ3q:-N9_T3de4qnQXZl5fQ3r:b-fvhdkr) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/config/config.go#L33)):*
> ```Go
> 		if envValue != "" {
> 			if err = flag.Value.Set(envValue); err != nil {
> 				break
> ```

`return err` for easier readability?
___
*[`pkg/config/config.go` line 38 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_T76L6NXvnE9YxwwU:-N9_T76L6NXvnE9YxwwV:b-4td9bw) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/config/config.go#L38)):*
> ```Go
> 	}
> 
> 	return err
> ```

`return nil`
___
*[`pkg/config/config_test.go` line 13 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_TEm3Codc2256X9_2:-N9_TEm3Codc2256X9_3:b-cqxwh1) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/config/config_test.go#L13)):*
> ```Go
> 
> func TestWithEnv_WithPrefix(t *testing.T) {
> 	flagSet := pflag.NewFlagSet("temp", pflag.ExitOnError)
> ```

`ExitOnError` is probably not good for unit tests
___
*[`pkg/http/http.go` line 64 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_ODlu30d6xcffDESP:-N9_ODlu30d6xcffDESQ:b-o4yde0) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L64)):*
> ```Go
> func (s Server) Start(listenAddress string, shutdownSig <-chan struct{}, forceShutdownTimeout time.Duration) {
> 	// Start server
> 	exitListening := make(chan interface{}, 1)
> ```

Capacity is not needed here. From my experience, setting capacity on channels if it's not needed creates a lot of troubles because if receiver dies for any reason, sender is still able to send data to the channel causing a false notion that app works correctly, instead of panicking because of deadlock.
___
*[`pkg/http/http.go` line 65 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_PCut8C97vYF56g5q:-N9_PCut8C97vYF56g5r:bs8bz8k) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L65)):*
> ```Go
> 	// Start server
> 	exitListening := make(chan interface{}, 1)
> 	go func() {
> ```

panics are not handled
___
*[`pkg/http/http.go` line 66 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Ofqa-8nI_3QJyWwQ:-N9_Ofqa-8nI_3QJyWwR:bxge8pe) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L66)):*
> ```Go
> 	exitListening := make(chan interface{}, 1)
> 	go func() {
> 		listener, err := net.Listen("tcp", listenAddress)
> ```

missing `defer listener.Close()`
___
*[`pkg/http/http.go` line 66 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_PlB1BdOFsKXpCP5-:-N9_PlB1BdOFsKXpCP50:bkpkcmj) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L66)):*
> ```Go
> 	exitListening := make(chan interface{}, 1)
> 	go func() {
> 		listener, err := net.Listen("tcp", listenAddress)
> ```

listener might be created outside the goroutine which should make your life easier because you don't need to deal with error inside goroutine
___
*[`pkg/http/http.go` line 71 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_PInwDxaXPiF0jYTb:-N9_PInwDxaXPiF0jYTc:b-jqrk07) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L71)):*
> ```Go
> 		if err != nil {
> 			s.logger.Info("unable to listen on address", zap.Error(err))
> 			return
> ```

error should be returned and logged outside the `http` package
___
*[`pkg/http/http.go` line 75 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_NEem9z2q6SRQQU77:-N9_NEenCwUhKGlE_fjY:bo2e2ll) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L75)):*
> ```Go
> 
> 		s.logger.Info("Started listening for http connections", zap.String("address", listenAddress))
> 		if err := http.Serve(listener, s.Echo); err != nil && !errors.Is(err, http.ErrServerClosed) {
> ```

Error should be returned here and in consequence application should exit. Otherwise application is left in zombie state waiting for signal
___
*[`pkg/signal/signal.go` line 12 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Kzy8EGPLUIH1A9Nl:-N9_Kzy8EGPLUIH1A9Nm:bvna5qs) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/signal/signal.go#L12)):*
> ```Go
> 
> // TerminateSignal returns a signal
> func TerminateSignal(opts ...opt) context.Context {
> ```

exported function should use exported types, so `opt` should be exported
___
*[`pkg/signal/signal.go` line 18 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9 [...]

2022-08-16 09:06 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 29 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_JMfe96D7G6tTa9-n:-N9_iDQl5sndrRNwocP3:bi2gcoe) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/main.go#L43)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

it seems to me that you could add logger to `ctxQuit` and use single context instead of two
</blockquote></details>

I don't think that is a good idea, ctxQuit has a specific usecase that it carries a shutdown signal.
___
*[`app/parse_addr_test.go` line 37 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N96afj7B58P1NCNC1Qr:-N9_idlBEg3ZoqqsaHRp:bd5kec3) ([raw file](https://github.com/coreumfoundation/faucet/blob/26dc81c63a87aafd3fd7e35d92e0fcfb946efb24/app/parse_addr_test.go#L37)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

eventually `tc := tc`
</blockquote></details>

this works as well. 
___
*[`http/errors.go` line 27 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_UcM74Q2XS-5GFzBZ:-N9_qq5b8whdmd4v6Qp9:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/http/errors.go#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

error -> Error
</blockquote></details>

Done.
___
*[`http/errors.go` line 85 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Ut6XCwmVKIMoDSDR:-N9_j0c5Bp9LlQg2bcEx:b8eghqc) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/http/errors.go#L85)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This should not be done like this. HTTP handler should return correct `APIError` directly.
</blockquote></details>

I don't know what you mean by correct APIError. You probably mean the concrete type instead of the interface ? we may need to talk on call so I will know what exactly you mean. 
___
*[`pkg/config/config.go` line 19 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_SXX77GHUfrxQNzXu:-N9_jHk32_kpk4Jaxgr5:bvvitaw) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/config/config.go#L19)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Couldn't this logic be implemented inside `VisitAll` directly?
</blockquote></details>

VisitAll does not allow to exit the loop if error occurred.
___
*[`pkg/config/config.go` line 32 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Sm9F4hKQbQyCnbpO:-N9_jWgz4Rh45zFBMiLi:bp5lrfx) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/config/config.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you could set default value of the flag, then `--help` will print them correctly and 

```go
		if flag.Changed {
			continue
		}
```

won't be needed
</blockquote></details>

I tried that, it is not possible to change the default value of the flag (it will not take affect on the pointer value). However it worked in coreum repo when we did it with cobra, my guess is that cobra is doing some internal processing which allows our rewrites to work. 
___
*[`pkg/config/config.go` line 33 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_T3de4qnQXZl5fQ3q:-N9_k4FkE7lC2FwzdbN-:b-56m3q3) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/config/config.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`return err` for easier readability?
</blockquote></details>

excellent suggestion. 
___
*[`pkg/config/config.go` line 38 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_T76L6NXvnE9YxwwU:-N9_k7mg3rx-JfXnKFzK:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/config/config.go#L38)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`return nil`
</blockquote></details>

Done.
___
*[`pkg/config/config_test.go` line 13 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_TEm3Codc2256X9_2:-N9_k_Vm1b7rrd2CPycC:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/config/config_test.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`ExitOnError` is probably not good for unit tests
</blockquote></details>

Done.
___
*[`pkg/http/http.go` line 64 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_ODlu30d6xcffDESP:-N9_lNaR7A2w2L48ol3d:bb6un1j) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L64)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Capacity is not needed here. From my experience, setting capacity on channels if it's not needed creates a lot of troubles because if receiver dies for any reason, sender is still able to send data to the channel causing a false notion that app works correctly, instead of panicking because of deadlock.
</blockquote></details>

Done
___
*[`pkg/http/http.go` line 65 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_PCut8C97vYF56g5q:-N9_rhR3AIg8bJZb8-i7:b-krvn7i) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L65)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

panics are not handled
</blockquote></details>

I don't think we need to handle panics here. first of all there are 4 lines of code 3 of which are logging or error checking and one line of code that does something. secondly if application panics at this stage of runtime, we don't get much by recovering error. 
___
*[`pkg/http/http.go` line 66 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Ofqa-8nI_3QJyWwQ:-N9_mDqWAya0JIm3YI5B:b3rvr06) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L66)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

missing `defer listener.Close()`
</blockquote></details>

shutdown calls that internally, I can add it as an extra step if you like. 
___
*[`pkg/http/http.go` line 66 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_PlB1BdOFsKXpCP5-:-N9_makJC_KEMbUtW7CD:b-hpkznd) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L66)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

listener might be created outside the goroutine which should make your life easier because you don't need to deal with error inside goroutine
</blockquote></details>

good idea. 
___
*[`pkg/http/http.go` line 71 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_PInwDxaXPiF0jYTb:-N9_nW4g5X4Vq9MAVmrD:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L71)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

error should be returned and logged outside the `http` package
</blockquote></details>

Done.
___
*[`pkg/http/http.go` line 75 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_NEem9z2q6SRQQU77:-N9_nj-r43mBjHH8ppQb:b-gnxer8) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3 [...]

2022-08-17 10:17 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 17 of 18 files reviewed, 19 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_JMfe96D7G6tTa9-n:-N9eeL6p2G3W_mqRsyTE:b-g75osl) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/main.go#L43)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This is a common use case for ctx, that some function should exit when ctx is canceled. I don't see a purpose for having two of them: one containing logger, second one supporting cancellation. That's the idea of `ctx` - to have a single one.
</blockquote></details>

for instance, in case we have db connections, they should not abandon what they do. Or in the case of coreum client, it should not abandon on flight transactions. 
___
*[`http/errors.go` line 85 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Ut6XCwmVKIMoDSDR:-N9eevyuEvBeIS7X02p0:b-r8le7k) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/http/errors.go#L85)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

No, I mean that handler should directly return some `APIError`, without maintaining `error -> APIError` map
</blockquote></details>

but then each API should build this mapper inside and know how to map application errors (like address too long and so on) into APIError. 
___
*[`pkg/config/config.go` line 32 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Sm9F4hKQbQyCnbpO:-N9efOrN4_1Y48Ru5Dni:bs279pk) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/config/config.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But we still would love to rpint correct default values on `--help`. Otherwise people will be missleaded.
</blockquote></details>

the default values will not be read from env, I don't think that is the behavior that people expect. 
___
*[`pkg/config/config.go` line 13 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9aJweh6OL8tZnQYCOZ:-N9fI0779XW9JT2mbWmd:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/eef97506ccb6094097971acb8bf487a7dc2bf79f/pkg/config/config.go#L13)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Now this "global" `err` seems to be not needed
</blockquote></details>

Done.
___
*[`pkg/http/http.go` line 65 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_PCut8C97vYF56g5q:-N9ef_f61Fl3uwDOv2RS:b-1hztjh) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L65)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Those 4 lines of code spin entire http server. I know that this http server is used by millions of people but my opinion is very strict here: every piece of code might panic, and that panic can't transition our application to a zombie state where it is still running but requests are not handled.
</blockquote></details>

I tend to disagree that panic must be handled here, we will not recover the application and the application will exit after the recover function regardless.
___
*[`pkg/http/http.go` line 74 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9aKxPe25klEfY-GXw3:-N9f6oim3kdQNIYpfEiS:b7tdlwq) ([raw file](https://github.com/coreumfoundation/faucet/blob/eef97506ccb6094097971acb8bf487a7dc2bf79f/pkg/http/http.go#L74)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Here and two lines above goroutine will hang on trying to send error or `nil` to `exitListening` if value appeared in `shutdownSig`. In this case problem will be hidden because application will kill all the zombie goroutines on exit but as I said in another place it is not a good practice to design applications this way because we will pay the price in the future. To solve this you may add capacity back to `exitListening` channel (worse solution) or implement structured concurrency (better solution) :-).
</blockquote></details>

I don't get why it would hang, it will write to channel and the channel will get garbage collected. Moreover not specifying a channel size is like specifying 1 so I see no difference.
___
*[`pkg/signal/signal.go` line 23 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_R68b2gyTidzCHnMD:-N9fHaXrEBAKN2CE7PVY:bukghbp) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/signal/signal.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Scenario is really simple:
- http server exits because of an error
- application exits
- the goroutine here does not exit gracefully because nothing entered `sigChan`, it will be killed on the exit of application
</blockquote></details>

I don't know how it would be solved even with `structured concurrency`
___
*[`pkg/signal/signal.go` line 28 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_LL83D0Ep_wiYsiY_:-N9fHm86AkHgw_I-QLGy:bl1gy9p) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/signal/signal.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

IMO the option for development stage if your app hangs is `kill -9 <pid>`
</blockquote></details>

@ysv would you care to comment ?


<!-- Sent from Reviewable.io -->

2022-08-18 05:47 UTC, wojtek-coreum reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 15 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`main.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_JMfe96D7G6tTa9-n:-N9jPNHp4QSww4FooeTJ:b33rdmz) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/main.go#L43)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

for instance, in case we have db connections, they should not abandon what they do. Or in the case of coreum client, it should not abandon on flight transactions. 
</blockquote></details>

We discussed it in a meeting. Single `ctx` might do the job as well.
___
*[`pkg/config/config.go` line 32 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Sm9F4hKQbQyCnbpO:-N9jPaGlC8I1mc_j-4QL:b8uxhmm) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/config/config.go#L32)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the default values will not be read from env, I don't think that is the behavior that people expect. 
</blockquote></details>

We discussed in a meeting that this is exactly what people expect
___
*[`pkg/http/http.go` line 65 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_PCut8C97vYF56g5q:-N9jPrVp4RVlggRIyF_c:b-kw5jxj) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L65)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I tend to disagree that panic must be handled here, we will not recover the application and the application will exit after the recover function regardless.
</blockquote></details>

We discussed it in a meeting it's more about philosophy of using goroutines as we discussed it many times already. We may treat every goroutine indivdualy and decide case by case or have an unified way of starting and managing goroutines. We will develop it anyway at some point, the only question is if we want to learn this lesson the hard or easy way.
___
*[`pkg/http/http.go` line 74 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9aKxPe25klEfY-GXw3:-N9jQUl-5jz6pJQukBYM:bfbmv3k) ([raw file](https://github.com/coreumfoundation/faucet/blob/eef97506ccb6094097971acb8bf487a7dc2bf79f/pkg/http/http.go#L74)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't get why it would hang, it will write to channel and the channel will get garbage collected. Moreover not specifying a channel size is like specifying 1 so I see no difference.
</blockquote></details>

Discussed it in a meeting
___
*[`pkg/signal/signal.go` line 23 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_R68b2gyTidzCHnMD:-N9jQd-b5bCDSK1z_rK3:b-j750bv) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/signal/signal.go#L23)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't know how it would be solved even with `structured concurrency`
</blockquote></details>

The way it is implemented in `parallel` is that every goroutine receives `ctx` which, in basic scenario, is canceled when any goroutine returns. It means that `ctx` is a single source of truth. So the schema is like this:

```go
ctx := ... // context comes from magic place


httpServer := ...
go func() {
   err := httpServer.ListenAndServe()
   return // when goroutine returns, `ctx` is automatically canceled meaning that all the other goroutines should exit
}()

go func() {
   <-ctx.Done() // waiting until any other goroutine exits
   httpServer.Shutdown()
}()

go func() {
   sigChan := make(chan os.Signal, 1)
   signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)

   select {
   case <-sigChan:
      // exit because of signal, `ctx` is canceled automatically on exit and all the other goroutines will exit
   case <-ctx.Done():
      // other goroutine terminated for whatever reason, so this one should exit too to prevent deadlock
   }
}()

// wait until all goroutines exit
```

So there are (only!) two exit conditions for each goroutine:
- internal - related to business logic implemented by the goroutine
- external - always signaled by `<-ctx.Done()`, caused by any other goroutine in the application

So there are two concepts working together:
- structured concurrency
- `ctx` used to communicate exit conditions between goroutines

On the other hand people usually write goroutines in the way that every goroutine gives it's own condition saying that application should exit. It means that if you have 10 goroutines, there are 10 conditions every goroutine must check to decide if it should exit gracefully or continue its operation.


<!-- Sent from Reviewable.io -->

2022-08-18 05:53 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 15 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`pkg/signal/signal.go` line 23 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_R68b2gyTidzCHnMD:-N9jV03yBF50YyUCSVMo:b6ndyaw) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/signal/signal.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

The way it is implemented in `parallel` is that every goroutine receives `ctx` which, in basic scenario, is canceled when any goroutine returns. It means that `ctx` is a single source of truth. So the schema is like this:

```go
ctx := ... // context comes from magic place


httpServer := ...
go func() {
   err := httpServer.ListenAndServe()
   return // when goroutine returns, `ctx` is automatically canceled meaning that all the other goroutines should exit
}()

go func() {
   <-ctx.Done() // waiting until any other goroutine exits
   httpServer.Shutdown()
}()

go func() {
   sigChan := make(chan os.Signal, 1)
   signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)

   select {
   case <-sigChan:
      // exit because of signal, `ctx` is canceled automatically on exit and all the other goroutines will exit
   case <-ctx.Done():
      // other goroutine terminated for whatever reason, so this one should exit too to prevent deadlock
   }
}()

// wait until all goroutines exit
```

So there are (only!) two exit conditions for each goroutine:
- internal - related to business logic implemented by the goroutine
- external - always signaled by `<-ctx.Done()`, caused by any other goroutine in the application

So there are two concepts working together:
- structured concurrency
- `ctx` used to communicate exit conditions between goroutines

On the other hand people usually write goroutines in the way that every goroutine gives it's own condition saying that application should exit. It means that if you have 10 goroutines, there are 10 conditions every goroutine must check to decide if it should exit gracefully or continue its operation.
</blockquote></details>

Compare this concept with your code where `shutdownSig` and `exitListening` must be tightly coupled to prevent deadlocks. Imagine that you need to add another goroutine, to support queue of requests and another N goroutines broadcasting transactions using N accounts. Giving alltogether like N+4 goroutines.


<!-- Sent from Reviewable.io -->

2022-08-18 10:22 UTC, ysv reviewed
> Reviewed 1 of 9 files at r1, 2 of 7 files at r2, 1 of 1 files at r3, 5 of 11 files at r6, 1 of 2 files at r7, 6 of 7 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 26 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @xlab)

___
*[`go.mod` line 4 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fsQSM0uY9R0RYPpRW:-N9fsQSM0uY9R0RYPpRX:b-62kx5z) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/go.mod#L4)):*
> ```XML
> 
> go 1.18
> ```

should we use go 1.19 ?
___
*[`go.mod` line 5 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fs1Fl0mtva-zES2IE:-N9fs1Fl0mtva-zES2IF:btl09mm) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/go.mod#L5)):*
> ```XML
> go 1.18
> 
> replace github.com/gogo/protobuf => github.com/regen-network/protobuf v1.3.3-alpha.regen.1
> ```

can you pls add TODO here to remove this replace because after migration to cosmos 0.46 it is not needed AFAIK

You can confirm with Dmitry once migr to new version is done
___
*[`main.go` line 47 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xu85m16jWKSaqNUBx:-N9fvf4H72OECR9z0z8x:b-2narl) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/main.go#L47)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

refactoring this is easy, once that method is removed, the compiler will complaing and we will adjust. This is not a big issue IMO.
</blockquote></details>

yes 
I also don't like it needs to be addressed ASAP (of course not this PR but one of the next)
___
*[`main.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_JMfe96D7G6tTa9-n:-N9fvBsZ-s7uukMdu5cO:bq2r59p) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/main.go#L43)):*
I agree with @wojtek-coreum and that is what I mentioned in a previous comment

> for instance, in case we have db connections, they should not abandon what they do. Or in the case of coreum client, it should not abandon on flight transactions.
do you mean that request context (which is a child of this one) gets cancelled right after receiving this signal ? Because I'm not sure about it

Needs discussion
___
*[`main.go` line 15 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fshSF9T_R1vWsVTT7:-N9fshSF9T_R1vWsVTT8:b-u0b11t) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/main.go#L15)):*
> ```Go
> 	"go.uber.org/zap"
> 
> 	coreumApp "github.com/CoreumFoundation/coreum/app"
> ```

I'm not sure what the naming convention in general, but I prefer to just join words without camelCase because of multiple reasons

e.g `coreumapp` & `coreumclient` here
___
*[`main.go` line 37 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9ftnvLEbwoaSXfNlCB:-N9ftnvLEbwoaSXfNlCC:b21o10j) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/main.go#L37)):*
> ```Go
> 	loggerConfig, loggerFlagRegistry := logger.ConfigureWithCLI(logger.ServiceDefaultConfig)
> 	log := logger.New(loggerConfig)
> 	ctxQuit := signal.TerminateSignal(
> ```

Critical:
I disagree with the context approach you took here.
`func TerminateSignal` should accept context as argument, operate with it and return child ctx created from original one.

Because currently you have 2 independent ctx both created from context.Background in main.go & signal.go while it should be like this:

```go
func main() {
	loggerConfig, loggerFlagRegistry := logger.ConfigureWithCLI(logger.ServiceDefaultConfig)
	log := logger.New(loggerConfig)
	
	ctx := signal.TerminateSignal(
		context.Background(),
		signal.WithForceTimeout(30*time.Second),
		signal.WithForceOnSecondSignal(true),
	)

	ctx = logger.WithLogger(ctx, log)
        // ...
 }
```
___
*[`main.go` line 46 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fxbq13Wbs5dJyekFw:-N9fxbq13Wbs5dJyekFx:b-9q5r6v) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/main.go#L46)):*
> ```Go
> 	flagSet := pflag.NewFlagSet("faucet", pflag.ExitOnError)
> 	loggerFlagRegistry(flagSet)
> 	config := getConfig(log, flagSet)
> ```

```
Variable 'config' collides with imported package name
```

rename to `conf` ?
___
*[`main.go` line 58 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fwXCM0FhQXmaIAl0s:-N9fwXCM0FhQXmaIAl0t:b-ynuf2r) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/main.go#L58)):*
> ```Go
> 
> 	network.SetupPrefixes()
> 	cl := coreum.New(
> ```

non-blocking:

I'm thinking of abstracting from coreum client for now since it is WIP and it is taking too long to get it finalized.
I would probably suggest to define dummy client for now with a similar func signature doing nothing for now so you don't get blocked by client and later you just replace dummy with a real client.

E.g
```
type Client interface {
 func TransferToken(...) ...
}

type DummyClient struct {}

func (d *DummyClient) TransferToken(...)... {
   // do nothing
}
```

And temporary just use it in app for now. So we get this PR merged independently 

P.S. if you ask me I would say that here it is reasonable usage of interfaces defined on consumer side
___
*[`main.go` line 75 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9gPafm7h3a0n4Rz-KB:-N9gPafm7h3a0n4Rz-KC:bto9iqh) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/main.go#L75)):*
> ```Go
> 	}
> 
> 	app := app.New(cl, network, transferAmount, privateKeys[0])
> ```

app conflicts with the pkg name

Maybe use `application` ?
___
*[`app/app.go` line 17 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9gPzOX47DvQ7POzcj8:-N9gPzOX47DvQ7POzcj9:b4wcgl3) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/app/app.go#L17)):*
> ```Go
> 	fundsPrivateKey types.Secp256k1PrivateKey
> 	client          coreum.Client
> 	transferAmount  types.Coin
> ```

since we are likely to drop this type I would probably suggest to not use it now but just pass as a number or some internal struct
___
*[`http/errors.go` line 85 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Ut6XCwmVKIMoDSDR:-N9g-dDp00lBrh0_DeOR:b1e89a2) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/http/errors.go#L85)):*
> No, I mean that handler should directly return some APIError, without maintaining error -> APIError map

Probably yes because having a centralised middleware mapping all errors is not the best thing. What is more same business error might mean different things in http level.

That is why during our call with @miladz68 I mentioned that middleware is probably not the best solution. And each handler should map errors separatelly


But I don't insist on refactoring it right now for limiting over engineering 
So @miladz68 as you choose but for me I would do this on handler level
___
*[`http/http.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9gQqCx18tBKKMCr8cH:-N9gQqCx18tBKKMCr8cI:b2l9k4c) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L26)):*
> ```Go
> 
> // ListenAndServe starts listening for http requests
> func (h HTTP) ListenAndServe(ctx context.Context, port int) error {
> ```

I would also add /version endpoint because it is essential

But the PR is already to big so just put a TODO and do this in a next PR
___
*[`http/http.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9gQbZO0d0dsCqbsBSj:-N9gQbZO0d0dsCqbsBSk [...]

2022-08-18 12:06 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 26 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 58 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fwXCM0FhQXmaIAl0s:-N9knJ704fnye7-6pdXP:b-ixaft1) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/main.go#L58)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

non-blocking:

I'm thinking of abstracting from coreum client for now since it is WIP and it is taking too long to get it finalized.
I would probably suggest to define dummy client for now with a similar func signature doing nothing for now so you don't get blocked by client and later you just replace dummy with a real client.

E.g
```
type Client interface {
 func TransferToken(...) ...
}

type DummyClient struct {}

func (d *DummyClient) TransferToken(...)... {
   // do nothing
}
```

And temporary just use it in app for now. So we get this PR merged independently 

P.S. if you ask me I would say that here it is reasonable usage of interfaces defined on consumer side
</blockquote></details>

But the code here actually works (yes, it needs to be refactored once client is there) so why to change it to sth not working?
___
*[`http/errors.go` line 85 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Ut6XCwmVKIMoDSDR:-N9knz_h3NbIA6PDmCLR:bamhsjp) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/http/errors.go#L85)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> No, I mean that handler should directly return some APIError, without maintaining error -> APIError map

Probably yes because having a centralised middleware mapping all errors is not the best thing. What is more same business error might mean different things in http level.

That is why during our call with @miladz68 I mentioned that middleware is probably not the best solution. And each handler should map errors separatelly


But I don't insist on refactoring it right now for limiting over engineering 
So @miladz68 as you choose but for me I would do this on handler level
</blockquote></details>

IMO the entire issue with error conversion is introduced because we decided to split functionality between app layer and http layer, which is completely not needed here and makes our life harder without providing any benefits.
___
*[`pkg/http/http.go` line 64 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_ODlu30d6xcffDESP:-N9koOpdC4FJcrhWp0f6:b6i76fr) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L64)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> Capacity is not needed here. From my experience, setting capacity on channels if it's not needed creates a lot of troubles because if receiver dies for any reason, sender is still able to send data to the channel causing a false notion that app works correctly, instead of panicking because of deadlock.
 
I didn't get this.
I also tried this and seems that there is a slight difference
</blockquote></details>

Consider this example:

```go
queue := make(chan struct{}, 10)

// sender
go func() {
   for i := 0; i < 10; i++ {
      queue <- struct{}
   }
   close(queue)
}()

// receiver
go func() {
  for item := range queue {
     return // this is a bug
  }
}()

// wait until both goroutines exit
```

In this example application did sth and exited without error without giving any notion of the problem, despite the fact that some result somewhere is incorrect.

If you define `queue` without capacity: `queue := make(chan struct{})` application will panic automatically because of the deadlock giving you clear hint that something is wrong.  So defining capacity on channels if it's not really needed may cause problems to be hided.
___
*[`pkg/signal/signal.go` line 28 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_LL83D0Ep_wiYsiY_:-N9kq-Mj0Qv_QujPNA41:bxx7ez4) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/signal/signal.go#L28)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

If you ask me I see this package just receiving ctx then creating child context from it with cancellation and return it

I think using os.Exit is not a good practice 

That is what I was using before
```
func NewCtrlC(rootCtx context.Context) (context.Context, context.CancelFunc) {
	c := make(chan os.Signal, 1)
	signal.Notify(c, syscall.SIGINT, syscall.SIGTERM)

	ctx, cancel := context.WithCancel(rootCtx)

	go func() {
		<-c
		cancel()
	}()
	return ctx, cancel
}
```
</blockquote></details>

@ysv The fact that your function returns `cancel` is a sign of bad design IMO


<!-- Sent from Reviewable.io -->

2022-08-18 12:07 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 26 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/signal/signal.go` line 28 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_LL83D0Ep_wiYsiY_:-N9kqGeJ9PZFQF3K8UE6:b-eiay8a) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/signal/signal.go#L28)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

@ysv The fact that your function returns `cancel` is a sign of bad design IMO
</blockquote></details>

Also `<-c` causes that this goroutine is just killed when application exits (it doesn't cause problems in this particular case but should be avoided IMO)


<!-- Sent from Reviewable.io -->

2022-08-18 12:21 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 27 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9ktMYN22Tp51GlIjha:-N9ktMYO-zamHgUX1jn5:b-lv3xse) (no related file):*
Non-blocking: In other PR I was requested to store private key as mnemonics, not bytes. Maybe it could be nice to use this form everywhere then? I mean faucet could read the mnemonic from file instead of the key?

___


<!-- Sent from Reviewable.io -->

2022-08-21 08:13 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 10 of 18 files reviewed, 27 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9ktMYN22Tp51GlIjha:-N9zBGnaAW9Uqrv_0GbP:b-k9vby3) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Non-blocking: In other PR I was requested to store private key as mnemonics, not bytes. Maybe it could be nice to use this form everywhere then? I mean faucet could read the mnemonic from file instead of the key?
</blockquote></details>

can you share a link to the PR ?

___
___
*[`go.mod` line 4 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fsQSM0uY9R0RYPpRW:-N9zBXz41k9o0lnTRJ5o:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/go.mod#L4)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should we use go 1.19 ?
</blockquote></details>

Done.
___
*[`go.mod` line 5 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fs1Fl0mtva-zES2IE:-N9zBbd_93Fa8hL2fgq1:b-taw83z) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/go.mod#L5)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

can you pls add TODO here to remove this replace because after migration to cosmos 0.46 it is not needed AFAIK

You can confirm with Dmitry once migr to new version is done
</blockquote></details>

They have not fixed the issue in 0.46. (look [here](https://github.com/cosmos/cosmos-sdk/blob/v0.46.0/go.mod#L158)). More over a todo is not necessary because if they remove this from cosmos sdk then we will get an error if we don't remove it, so we will know when to remove it. 
___
*[`main.go` line 43 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_JMfe96D7G6tTa9-n:-N9zFwjk2gYcD-WhpeWu:b-2i6n11) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/main.go#L43)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I agree with @wojtek-coreum and that is what I mentioned in a previous comment

> for instance, in case we have db connections, they should not abandon what they do. Or in the case of coreum client, it should not abandon on flight transactions.
do you mean that request context (which is a child of this one) gets cancelled right after receiving this signal ? Because I'm not sure about it

Needs discussion
</blockquote></details>

applied changes, we can discuss it if you like @ysv.
___
*[`main.go` line 15 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fshSF9T_R1vWsVTT7:-N9zEzf729YARTvXH9KP:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/main.go#L15)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I'm not sure what the naming convention in general, but I prefer to just join words without camelCase because of multiple reasons

e.g `coreumapp` & `coreumclient` here
</blockquote></details>

Done.
___
*[`main.go` line 37 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9ftnvLEbwoaSXfNlCB:-N9zFB4p0y5d6uQZb3vP:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/main.go#L37)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Critical:
I disagree with the context approach you took here.
`func TerminateSignal` should accept context as argument, operate with it and return child ctx created from original one.

Because currently you have 2 independent ctx both created from context.Background in main.go & signal.go while it should be like this:

```go
func main() {
	loggerConfig, loggerFlagRegistry := logger.ConfigureWithCLI(logger.ServiceDefaultConfig)
	log := logger.New(loggerConfig)
	
	ctx := signal.TerminateSignal(
		context.Background(),
		signal.WithForceTimeout(30*time.Second),
		signal.WithForceOnSecondSignal(true),
	)

	ctx = logger.WithLogger(ctx, log)
        // ...
 }
```


</blockquote></details>

Done.
___
*[`main.go` line 46 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fxbq13Wbs5dJyekFw:-N9zG6XE98yxZm74-7z0:blo89ya) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/main.go#L46)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

```
Variable 'config' collides with imported package name
```

rename to `conf` ?
</blockquote></details>

Done. renamed to `cfg`,
___
*[`main.go` line 58 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fwXCM0FhQXmaIAl0s:-N9zQ0RM4X_6KDiM4lDG:bk3gd5x) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/main.go#L58)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But the code here actually works (yes, it needs to be refactored once client is there) so why to change it to sth not working?
</blockquote></details>

I agree that if we want to merge this PR we should do it as it is, since it is a working code. 
___
*[`main.go` line 75 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9gPafm7h3a0n4Rz-KB:-N9zGncG6Jf125jhPEep:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/main.go#L75)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

app conflicts with the pkg name

Maybe use `application` ?
</blockquote></details>

Done.
___
*[`app/app.go` line 17 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9gPzOX47DvQ7POzcj8:-N9zH1hQDvxqEnDNBs0W:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/app/app.go#L17)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

since we are likely to drop this type I would probably suggest to not use it now but just pass as a number or some internal struct
</blockquote></details>

Done.
___
*[`http/errors.go` line 85 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Ut6XCwmVKIMoDSDR:-N9zLj8M5bvFnN7MVNOQ:b-vcdc9s) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/http/errors.go#L85)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

IMO the entire issue with error conversion is introduced because we decided to split functionality between app layer and http layer, which is completely not needed here and makes our life harder without providing any benefits.
</blockquote></details>

@ysv FYI this function does not live in middleware, it is in http layer of faucet. I will keep it as it is. 
___
*[`http/http.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9gQqCx18tBKKMCr8cH:-N9zMCL_B8MCHAuzroNw:b-5wez1p) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I would also add /version endpoint because it is essential

But the PR is already to big so just put a TODO and do this in a next PR
</blockquote></details>

what exactly is /version endpoint supposed to do ?
___
*[`http/http.go` line 28 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9gQbZO0d0dsCqbsBSj:-N9zM9QPB1xTGMh6r3TE:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L28)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

![image.pn [...]

2022-08-22 08:50 UTC, wojtek-coreum requested changes
> Reviewed 5 of 8 files at r10, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 29 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9ktMYN22Tp51GlIjha:-NA3dhS_D1kqelj7TZKJ:b986c3j) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

can you share a link to the PR ?
</blockquote></details>

https://reviewable.io/reviews/CoreumFoundation/crust/63#-

___
___
*[`main.go` line 36 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3eFm3CAAEQJR-InGQ:-NA3eFm3CAAEQJR-InGR:bmxsoke) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/main.go#L36)):*
> ```Go
> 	loggerConfig, loggerFlagRegistry := logger.ConfigureWithCLI(logger.ServiceDefaultConfig)
> 	log := logger.New(loggerConfig)
> 	ctx := signal.TerminateSignal(context.Background())
> ```

you could write

```go
logger.WithLogger(context.Background(), log)
```

here so `TerminateSignal` function could log some stuff too, and it would be nice if it logs stuff saying that signal was received etc. because later on we will run it in kubernetes or sth like that and if we see in logs that app exited we would like to be able to understand why it happened
___
*[`main.go` line 39 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3eyJj0kjxpxa99n_B:-NA3eyJk6RqAY12o2tHq:biwh2t5) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/main.go#L39)):*
> ```Go
> 
> 	ctx = logger.WithLogger(ctx, log)
> 	flagSet := pflag.NewFlagSet("faucet", pflag.ContinueOnError)
> ```

why was it changed to `ContinueOnError`?
___
*[`main.go` line 92 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3fOaU74znse0qOJdo:-NA3fOaU74znse0qOJdp:b-2lt1xs) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/main.go#L92)):*
> ```Go
> 
> func getConfig(log *zap.Logger, flagSet *pflag.FlagSet) cfg {
> 	chainID := flagSet.String(flagChainID, string(coreumapp.Devnet), "The network chain ID")
> ```

why not `DefaultChainID`?
___
*[`main.go` line 98 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3fnbH9hFQVYe2NIgJ:-NA3fnbH9hFQVYe2NIgK:b-zcsqot) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/main.go#L98)):*
> ```Go
> 	keyFile := flagSet.String(flagPrivKeyFile, "private_keys_unarmored_hex.txt", "path to file containing hex encoded unarmored private keys, each line must contain one private key")
> 	help := flagSet.BoolP("help", "h", false, "prints help")
> 	_ = flagSet.Parse(os.Args[1:])
> ```

you set `ContinueOnError` so now you must handle error here, it might happen if iuser provides string for a flag requiring int. But I don't understand why you stopped using default `--help` provided by `pflag`.
___
*[`main.go` line 105 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3fW9ODCzzxt2wZamS:-NA3fW9ODCzzxt2wZamT:b-181n3j) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/main.go#L105)):*
> ```Go
> 	return cfg{
> 		chainID:         coreumapp.ChainID(*chainID),
> 		node:            *node,
> ```

Here and in the lines below. There are `*Var` methods provided by `pflag` so you don't need to assign values manually
___
*[`http/http.go` line 44 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fyPCz0SbgmRA0W0Wi:-NA3gdUXEdNPLbx1Casr:b-aojhq4) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/http/http.go#L44)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
But it will not pass crust linter once we integrate it with crust repo. 
</blockquote></details>

so we probably should turn off that linter, otherwise we will have to put `nolint`s everywhere. And that linter is annoying anyway becaus eit complains about consts imported from dependencies.
___
*[`pkg/http/http.go` line 74 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3hEs4DvmGbFGcFzU3:-NA3hEs4DvmGbFGcFzU4:bbpsh7u) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/pkg/http/http.go#L74)):*
> ```Go
> 		defer func() {
> 			rec := recover()
> 			err = errors.Wrapf(err, "listen paniced %s", rec)
> ```

this and next line should be inside `if rec := recover(); rec != nil {` otherwise code didn't really panicked.
___
*[`pkg/http/http.go` line 79 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3h_tRCOJJvPpyrrCf:-NA3h_tRCOJJvPpyrrCg:b3mu3hy) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/pkg/http/http.go#L79)):*
> ```Go
> 		}()
> 		s.logger.Info("Started listening for http connections", zap.String("address", listenAddress))
> 		if err = http.Serve(listener, s.Echo); err != nil && !errors.Is(err, http.ErrServerClosed) {
> ```

if `err` is `http.ErrServerClosed` it should be returned only if `ctx` hasn't been canceled. Because if it has, it means this is normal expected shutdown, not an issue to investigate.
___
*[`pkg/logger/logger.go` line 27 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3iCKE89-B0As06C7d:-NA3iCKE89-B0As06C7e:b-pjpvbq) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/pkg/logger/logger.go#L27)):*
> ```Go
> )
> 
> // RegisterFlagsOnFlagSet registers internally defined flags on an the provided flagSet
> ```

remove "an"
___
*[`pkg/logger/logger.go` line 33 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3iHRwEnPn3-_8xTso:-NA3iHRwEnPn3-_8xTsp:b10vimj) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/pkg/logger/logger.go#L33)):*
> ```Go
> 	return func(toFlagSet *pflag.FlagSet) {
> 		fromFlagSet.VisitAll(func(f *pflag.Flag) {
> 			if !lo.Contains(exceptions, f.Name) {
> ```

Could you explain the idea behind `exceptions` please?
___
*[`pkg/signal/signal.go` line 23 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_R68b2gyTidzCHnMD:-NA3ijj06Gl4YeUx_6tr:b-aqehla) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/signal/signal.go#L23)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it to be done. `This goroutine is still ignored when http server exits because of an error.


<!-- Sent from Reviewable.io -->

2022-08-22 11:07 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 26 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9ktMYN22Tp51GlIjha:-NA4AJ3aCDppKjxiei1d:bda3nem) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

https://reviewable.io/reviews/CoreumFoundation/crust/63#-
</blockquote></details>

I see that it was mentioned to either use hex or mnemonic, I prefer hex encoded and I think I will keep this as is. 

___
___
*[`main.go` line 36 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3eFm3CAAEQJR-InGQ:-NA42ltyBUA49gLU5nNR:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/main.go#L36)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you could write

```go
logger.WithLogger(context.Background(), log)
```

here so `TerminateSignal` function could log some stuff too, and it would be nice if it logs stuff saying that signal was received etc. because later on we will run it in kubernetes or sth like that and if we see in logs that app exited we would like to be able to understand why it happened

</blockquote></details>

Done.
___
*[`main.go` line 39 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3eyJj0kjxpxa99n_B:-NA42wO-9b0NHhwUgAPT:bva816e) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/main.go#L39)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why was it changed to `ContinueOnError`?
</blockquote></details>

letover changes from when I was trying to fix the help command. Reverted.
___
*[`main.go` line 92 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3fOaU74znse0qOJdo:-NA433Yp05_yUJnMOpGw:beyvdbf) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/main.go#L92)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why not `DefaultChainID`?
</blockquote></details>

default chain ID is mainnet, we will never have a faucet for that.
___
*[`main.go` line 98 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3fnbH9hFQVYe2NIgJ:-NA4395u06OwIZOgowd6:b-zakxfm) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/main.go#L98)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you set `ContinueOnError` so now you must handle error here, it might happen if iuser provides string for a flag requiring int. But I don't understand why you stopped using default `--help` provided by `pflag`.
</blockquote></details>

reverted to ExitOnError
___
*[`main.go` line 105 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3fW9ODCzzxt2wZamS:-NA443Lh4jevLBVMl9np:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/main.go#L105)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Here and in the lines below. There are `*Var` methods provided by `pflag` so you don't need to assign values manually
</blockquote></details>

Done.
___
*[`http/http.go` line 44 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fyPCz0SbgmRA0W0Wi:-NA44Mym8CL8eGcl2PVW:bbv726u) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/http/http.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

so we probably should turn off that linter, otherwise we will have to put `nolint`s everywhere. And that linter is annoying anyway becaus eit complains about consts imported from dependencies.
</blockquote></details>

I think we need to configure the linter to use snake_case and fix our code base accordingly everywhere.
___
*[`pkg/http/http.go` line 74 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3hEs4DvmGbFGcFzU3:-NA45R915smewbc_0586:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/pkg/http/http.go#L74)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

this and next line should be inside `if rec := recover(); rec != nil {` otherwise code didn't really panicked.
</blockquote></details>

Done.
___
*[`pkg/http/http.go` line 79 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3h_tRCOJJvPpyrrCf:-NA465O45Cxf4Xa3_PTv:b89924i) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/pkg/http/http.go#L79)):*
> http.ErrServerClosed

is returned only when GracefulShutdown or Close is called, neither of those cases require the error to be returned. 
___
*[`pkg/logger/logger.go` line 27 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3iCKE89-B0As06C7d:-NA48TTfCZubsuc8c0U1:b9wq5xi) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/pkg/logger/logger.go#L27)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

remove "an"
</blockquote></details>

on a second thought, none of these need to be exposed to the outside worlds.
___
*[`pkg/logger/logger.go` line 33 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3iHRwEnPn3-_8xTso:-NA48_ZT0mbSAowO-HOL:b-yimod1) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/pkg/logger/logger.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Could you explain the idea behind `exceptions` please?
</blockquote></details>

the flags that we wish not to register on the external flagset. 
___
*[`pkg/signal/signal.go` line 23 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_R68b2gyTidzCHnMD:-NA4DcHHBB4lJcqu6Ngm:b-m8w0f6) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/signal/signal.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't see it to be done. `This goroutine is still ignored when http server exits because of an error.
</blockquote></details>

if http server is returned, the goroutine will exit, it is not being ignored. 


<!-- Sent from Reviewable.io -->

2022-08-22 11:38 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 14 of 18 files reviewed, 26 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/signal/signal.go` line 23 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_R68b2gyTidzCHnMD:-NA4Kz8Z3lJFdeCKzDUW:butf1h) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/signal/signal.go#L23)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

if http server is returned, the goroutine will exit, it is not being ignored. 
</blockquote></details>

I think we discussed this in the call and agreed that the go routine will no be left hanging.


<!-- Sent from Reviewable.io -->

2022-08-22 12:39 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 14 of 18 files reviewed, 26 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`pkg/signal/signal.go` line 23 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_R68b2gyTidzCHnMD:-NA4YhEmE_-JdYLmnfjh:bkku4ej) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/signal/signal.go#L23)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think we discussed this in the call and agreed that the go routine will no be left hanging.
</blockquote></details>

As discussed with Wojtek, the only way to fix this is to use something like parallel package, but it will not be resolved in this PR. 


<!-- Sent from Reviewable.io -->

2022-08-22 13:59 UTC, wojtek-coreum requested changes
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 20 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`main.go` line 92 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3fOaU74znse0qOJdo:-NA4pkRk3KUf7ZMC8-p2:bbakxq6) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/main.go#L92)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

default chain ID is mainnet, we will never have a faucet for that.
</blockquote></details>

good point, could you explicitly put an `if` which returns error or even panics if faucet for mainnet (containing `mainnet` word) is started?
___
*[`main.go` line 105 at r12](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA4qIGM0DqyTsSG6lfk:-NA4qIGM0DqyTsSG6lfl:bh43yry) ([raw file](https://github.com/coreumfoundation/faucet/blob/5f93048c8e9492d7ee346c35cef0b0ddf7e8aec8/main.go#L105)):*
> ```Go
> 	flagSet.Int64Var(&conf.transferAmount, flagTransferAmount, 1000000, "how much to transfer in each request")
> 	flagSet.StringVar(&conf.privateKeysFile, flagPrivKeyFile, "private_keys_unarmored_hex.txt", "path to file containing hex encoded unarmored private keys, each line must contain one private key")
> 	flagSet.BoolVarP(&conf.help, "help", "h", false, "prints help")
> ```

Why do you add it manually instead of depending on the built-in functionality of `pflag`?
___
*[`pkg/logger/logger.go` line 33 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3iHRwEnPn3-_8xTso:-NA4p5ue8zFbX9ZUAOtC:b-knmbsr) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/pkg/logger/logger.go#L33)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

the flags that we wish not to register on the external flagset. 
</blockquote></details>

so why are they present flags in the internal one?
___
*[`pkg/signal/signal.go` line 22 at r12](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA4pHhtEU144Y2pKqwt:-NA4pHhtEU144Y2pKqwu:bx3cdbs) ([raw file](https://github.com/coreumfoundation/faucet/blob/5f93048c8e9492d7ee346c35cef0b0ddf7e8aec8/pkg/signal/signal.go#L22)):*
> ```Go
> 	go func() {
> 		s := <-sigChan
> 		log.Info("received syscall", zap.Stringer("syscall", s))
> ```

Capital letter

syscall -> signal, syscalls are received by kernel


<!-- Sent from Reviewable.io -->

2022-08-23 07:57 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 17 of 18 files reviewed, 20 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 92 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3fOaU74znse0qOJdo:-NA8ZE9F7pBmsS0JC9Yx:bnxw5dz) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/main.go#L92)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

good point, could you explicitly put an `if` which returns error or even panics if faucet for mainnet (containing `mainnet` word) is started?
</blockquote></details>

OK. but I think the rounds of comments on PRs is getting too much. we should put a cap on it and not introduce too many. In regard to this change, I think that is too much. If someone gets a private key from mainnet, and explicitly says to run it against mainnet, it means they want to have a faucet there. Not all problems can be fixed programmatically. 
___
*[`main.go` line 105 at r12](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA4qIGM0DqyTsSG6lfk:-NA8_8cIBqRT6q44jd23:bc6yqvx) ([raw file](https://github.com/coreumfoundation/faucet/blob/5f93048c8e9492d7ee346c35cef0b0ddf7e8aec8/main.go#L105)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Why do you add it manually instead of depending on the built-in functionality of `pflag`?
</blockquote></details>

With the built-in functionality 
___
*[`client/coreum/coreum.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xg4vB2IvEQ7S5KtLt:-NA8gYxMCiVrCRdA-wx6:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/client/coreum/coreum.go#L41)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

discussed yesterday waiting for new client
</blockquote></details>

Done.
___
*[`pkg/logger/logger.go` line 33 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3iHRwEnPn3-_8xTso:-NA8gEe67rQyboQ8SoyE:b-rcm9jt) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/pkg/logger/logger.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

so why are they present flags in the internal one?
</blockquote></details>

to avoid printing help on internal flagset. 
___
*[`pkg/signal/signal.go` line 22 at r12](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA4pHhtEU144Y2pKqwt:-NA8gO3Y6CLalGZ6aYU9:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/5f93048c8e9492d7ee346c35cef0b0ddf7e8aec8/pkg/signal/signal.go#L22)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Capital letter

syscall -> signal, syscalls are received by kernel
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-23 08:04 UTC, wojtek-coreum requested changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 18 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`main.go` line 92 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3fOaU74znse0qOJdo:-NA8hk_YAxj2SCAbhdeK:by7jhbt) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/main.go#L92)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

OK. but I think the rounds of comments on PRs is getting too much. we should put a cap on it and not introduce too many. In regard to this change, I think that is too much. If someone gets a private key from mainnet, and explicitly says to run it against mainnet, it means they want to have a faucet there. Not all problems can be fixed programmatically. 
</blockquote></details>

I still would prefer to protect us against our own stupidity. This small `if` may save us. You know, from time to time not-so-responsible people may enter the company or someone just may have a bad day.
___
*[`main.go` line 105 at r12](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA4qIGM0DqyTsSG6lfk:-NA8iKu56E_xtTOSCdam:b3kre) ([raw file](https://github.com/coreumfoundation/faucet/blob/5f93048c8e9492d7ee346c35cef0b0ddf7e8aec8/main.go#L105)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

With the built-in functionality 
</blockquote></details>

?
___
*[`pkg/logger/logger.go` line 33 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3iHRwEnPn3-_8xTso:-NA8i_2M18gnxEkBHIb2:b169u2y) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/pkg/logger/logger.go#L33)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

to avoid printing help on internal flagset. 
</blockquote></details>

Looks like I don't understand the entire concept, let's discuss f2f after the meeting


<!-- Sent from Reviewable.io -->

2022-08-23 08:29 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 18 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 105 at r12](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA4qIGM0DqyTsSG6lfk:-NA8oF-44sV-q4mZQAXA:b-m9zt0v) ([raw file](https://github.com/coreumfoundation/faucet/blob/5f93048c8e9492d7ee346c35cef0b0ddf7e8aec8/main.go#L105)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

?
</blockquote></details>

haha, my brain has shut down mid comment. 
with the built-in functionality you get exit code 2 witch indicates an error, but asking for help is not really an error.


<!-- Sent from Reviewable.io -->

2022-08-23 11:47 UTC, wojtek-coreum requested changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 17 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`main.go` line 105 at r12](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA4qIGM0DqyTsSG6lfk:-NA9VyRn33MPhkYPsptV:bd7ou90) ([raw file](https://github.com/coreumfoundation/faucet/blob/5f93048c8e9492d7ee346c35cef0b0ddf7e8aec8/main.go#L105)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

haha, my brain has shut down mid comment. 
with the built-in functionality you get exit code 2 witch indicates an error, but asking for help is not really an error.
</blockquote></details>

But application started with `--help` also doesn't serve it primary purpose (for example http service does not serve requests). So returning non-zero exit code is reasonable IMO, so orchestrators (kubernetes, docker) are notified that sth went wrong.


<!-- Sent from Reviewable.io -->

2022-08-23 11:50 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 17 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 105 at r12](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA4qIGM0DqyTsSG6lfk:-NA9XAO542sAq8mu0I_h:byzhie4) ([raw file](https://github.com/coreumfoundation/faucet/blob/5f93048c8e9492d7ee346c35cef0b0ddf7e8aec8/main.go#L105)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But application started with `--help` also doesn't serve it primary purpose (for example http service does not serve requests). So returning non-zero exit code is reasonable IMO, so orchestrators (kubernetes, docker) are notified that sth went wrong.
</blockquote></details>

none of the applications in any linux/mac machine with exit with 2 status code if you ask for help. 
___
*[`pkg/logger/logger.go` line 33 at r11](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA3iHRwEnPn3-_8xTso:-NA9XNh2CRhSMebuzbzA:br6r4x0) ([raw file](https://github.com/coreumfoundation/faucet/blob/4d7367b1154dc3a64f08f4790e15af56e0c6c172/pkg/logger/logger.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Looks like I don't understand the entire concept, let's discuss f2f after the meeting
</blockquote></details>

Discussed in a call. 


<!-- Sent from Reviewable.io -->

2022-08-23 11:54 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 16 unresolved discussions (waiting on @xlab and @ysv)

___
*[`main.go` line 105 at r12](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA4qIGM0DqyTsSG6lfk:-NA9XyEXEBvZUYtAqf3D:btlixpk) ([raw file](https://github.com/coreumfoundation/faucet/blob/5f93048c8e9492d7ee346c35cef0b0ddf7e8aec8/main.go#L105)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

none of the applications in any linux/mac machine with exit with 2 status code if you ask for help. 
</blockquote></details>

yep, I also checked a few (less, bash, etc) and you are right, but those applications are not executed as services. IMO if service application exits for other reason than signal received, it should communicate non-0 code. @ysv ?

And another question is: do you have any specific reason for ignoring default behavior of `pflag`? Even if it returns 2, why do you care?


<!-- Sent from Reviewable.io -->

2022-08-23 12:57 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 16 unresolved discussions (waiting on @xlab and @ysv)

___
*[`main.go` line 105 at r12](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA4qIGM0DqyTsSG6lfk:-NA9lPs010jwskA1VGO_:b78xis0) ([raw file](https://github.com/coreumfoundation/faucet/blob/5f93048c8e9492d7ee346c35cef0b0ddf7e8aec8/main.go#L105)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

yep, I also checked a few (less, bash, etc) and you are right, but those applications are not executed as services. IMO if service application exits for other reason than signal received, it should communicate non-0 code. @ysv ?

And another question is: do you have any specific reason for ignoring default behavior of `pflag`? Even if it returns 2, why do you care?
</blockquote></details>

postgres is a service and it is a similar story, same goes for mongodb. 


<!-- Sent from Reviewable.io -->

2022-08-23 13:06 UTC, wojtek-coreum approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 16 unresolved discussions (waiting on @xlab and @ysv)

___
*[`main.go` line 105 at r12](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NA4qIGM0DqyTsSG6lfk:-NA9ny438R91TaZzEN39:bfpm8ri) ([raw file](https://github.com/coreumfoundation/faucet/blob/5f93048c8e9492d7ee346c35cef0b0ddf7e8aec8/main.go#L105)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

postgres is a service and it is a similar story, same goes for mongodb. 
</blockquote></details>

okay, you won :-)


<!-- Sent from Reviewable.io -->

2022-08-23 15:06 UTC, ysv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 7 unresolved discussions (waiting on @miladz68, @wojtek-coreum, @xlab, and @ysv)

___
*[`go.mod` line 5 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fs1Fl0mtva-zES2IE:-NAABQj-Chk0q-oaMytI:b1oojrg) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/go.mod#L5)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

They have not fixed the issue in 0.46. (look [here](https://github.com/cosmos/cosmos-sdk/blob/v0.46.0/go.mod#L158)). More over a todo is not necessary because if they remove this from cosmos sdk then we will get an error if we don't remove it, so we will know when to remove it. 
</blockquote></details>

oh that is not nice ...
I was hoping this will be resolved

ok lets keep
___
*[`main.go` line 58 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fwXCM0FhQXmaIAl0s:-NAABo88Dm7hp6sJGmhT:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/main.go#L58)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I agree that if we want to merge this PR we should do it as it is, since it is a working code. 
</blockquote></details>

ok
___
*[`main.go` line 75 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9gPafm7h3a0n4Rz-KB:-NAABpg_BgSowC7rHdbl:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/main.go#L75)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok
___
*[`http/errors.go` line 85 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_Ut6XCwmVKIMoDSDR:-NAACBx3-MZPa2uxsWdX:brr9mw7) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/http/errors.go#L85)):*
> which is completely not needed here and makes our life harder without providing any benefits.

it most cases it will have significant benefits.
E.g we can add cli to do all these things and we will likely handler domain errors in a differetnt way there because we don't need HTTP status, translations etc
___
*[`http/http.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9gQqCx18tBKKMCr8cH:-NAACr2BD7q_j3ztCz_G:b8yrpu3) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L26)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

what exactly is /version endpoint supposed to do ?
</blockquote></details>

example from another project to understand main idea

```
func (*server) Version() handler.Handler {
	return func(w http.ResponseWriter, r *http.Request) error {
		v := struct {
			Version string `json:"version"`
			Go      string `json:"go"`
		}{
			Version: version.Version,
			Go:      runtime.Version(),
		}

		return json.NewEncoder(w).Encode(v)
	}
}
```

just todo is fine for now
___
*[`http/http.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xgj-K3sQFqGCfS6ZS:-NAADK2A7BkJjfO4KINh:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L50)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it is actually a left over code. removed.
</blockquote></details>

ok
___
*[`http/http.go` line 70 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xguUx2NBXDtSPw8a3:-NAADI4NEYdimhzIxVM0:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L70)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok
___
*[`http/http.go` line 78 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xh1eS3isNVV2tAqTO:-NAADIj8EMAeToxWJaY9:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L78)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok
___
*[`http/http.go` line 44 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fyPCz0SbgmRA0W0Wi:-NAAD1Hd5aFbWfUuvSIT:b-klyix7) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/http/http.go#L44)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think we need to configure the linter to use snake_case and fix our code base accordingly everywhere.
</blockquote></details>

we need to check if we can fix our code base easily then yes 
___
*[`pkg/http/http.go` line 64 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_ODlu30d6xcffDESP:-NAADZgeAsBBvaz3fkt0:b-94h8ja) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/http/http.go#L64)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Consider this example:

```go
queue := make(chan struct{}, 10)

// sender
go func() {
   for i := 0; i < 10; i++ {
      queue <- struct{}
   }
   close(queue)
}()

// receiver
go func() {
  for item := range queue {
     return // this is a bug
  }
}()

// wait until both goroutines exit
```

In this example application did sth and exited without error without giving any notion of the problem, despite the fact that some result somewhere is incorrect.

If you define `queue` without capacity: `queue := make(chan struct{})` application will panic automatically because of the deadlock giving you clear hint that something is wrong.  So defining capacity on channels if it's not really needed may cause problems to be hided.
</blockquote></details>

yes I also checked this makes sense

Didn't know about this slight difference
___
*[`pkg/signal/signal.go` line 28 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_LL83D0Ep_wiYsiY_:-NAAE4ezDEnbzA58jZaN:binnjf0) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/signal/signal.go#L28)):*
> The fact that your function returns cancel is a sign of bad design IMO

well in the current implementation it is just ignored but the implementation is the same

> Also <-c causes that this goroutine is just killed when application exits (it doesn't cause problems in this particular case but should be avoided IMO)

WDYM ?


<!-- Sent from Reviewable.io -->

2022-08-24 06:22 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 7 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`http/http.go` line 26 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9gQqCx18tBKKMCr8cH:-NADU5S28A_p807x_dc3:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L26)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

example from another project to understand main idea

```
func (*server) Version() handler.Handler {
	return func(w http.ResponseWriter, r *http.Request) error {
		v := struct {
			Version string `json:"version"`
			Go      string `json:"go"`
		}{
			Version: version.Version,
			Go:      runtime.Version(),
		}

		return json.NewEncoder(w).Encode(v)
	}
}
```

just todo is fine for now
</blockquote></details>

Done.
___
*[`http/http.go` line 44 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fyPCz0SbgmRA0W0Wi:-NADV46_2qNOIOLjNc7s:b-h8kebx) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/http/http.go#L44)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we need to check if we can fix our code base easily then yes 
</blockquote></details>

anyways, this repo is not yet part of crust. So I would say we should merge it for now.


<!-- Sent from Reviewable.io -->

2022-08-24 06:22 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 7 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`http/http.go` line 50 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xgj-K3sQFqGCfS6ZS:-NADW0nqETdMeuH4lrLS:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L50)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.
___
*[`http/http.go` line 70 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xguUx2NBXDtSPw8a3:-NADW1Jg2i0z2w5xt004:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L70)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.
___
*[`http/http.go` line 78 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N8xh1eS3isNVV2tAqTO:-NADW1uED-kyyy8LeRMB:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/3ef5d0fd3363a441055f5fc74a926e193abe1883/http/http.go#L78)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-24 06:37 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 17 of 18 files reviewed, 7 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`http/http.go` line 44 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fyPCz0SbgmRA0W0Wi:-NADY6DQ95o1UIup3Tfz:b-8l8x1q) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/http/http.go#L44)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

anyways, this repo is not yet part of crust. So I would say we should merge it for now.
</blockquote></details>

every code we add to any repo should pass CI, so code or CI must be adjusted. There is a PR adding CI to faucet
___
*[`pkg/signal/signal.go` line 28 at r7](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9_LL83D0Ep_wiYsiY_:-NADYrDT24hvOqxzUOO7:b-dg0ylu) ([raw file](https://github.com/coreumfoundation/faucet/blob/04a2ce3c4e8023963c13ec5d3c264ded48478991/pkg/signal/signal.go#L28)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

> The fact that your function returns cancel is a sign of bad design IMO

well in the current implementation it is just ignored but the implementation is the same

> Also <-c causes that this goroutine is just killed when application exits (it doesn't cause problems in this particular case but should be avoided IMO)

WDYM ?
</blockquote></details>

- when http server exits because of some error, the application exits
- at the same time this goroutine is still blocked by `s := <-sigChan`

It means that this goroutine is silently killed, it means that if it has a `defer` block inside, that code is not called.
As I argued many times, writing goroutines is much more complex than people usually imagine. Using `go` keyword directly in any non-trivial case causes troubles.


<!-- Sent from Reviewable.io -->

2022-08-24 06:38 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 7 unresolved discussions (waiting on @xlab and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-24 06:58 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 7 unresolved discussions (waiting on @xlab and @ysv)

___
*[`http/http.go` line 44 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fyPCz0SbgmRA0W0Wi:-NADdJUeBkAIKUXoB9Yh:bl6lbo5) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/http/http.go#L44)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

every code we add to any repo should pass CI, so code or CI must be adjusted. There is a PR adding CI to faucet
</blockquote></details>

Ok, I will revert it to camel case for now so the CI passes. 


<!-- Sent from Reviewable.io -->

2022-08-24 09:00 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 7 unresolved discussions (waiting on @xlab and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-24 09:06 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 9 unresolved discussions (waiting on @miladz68, @xlab, and @ysv)

___
*[`main.go` line 81 at r14](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NAAF7J55JLNYQRY5gh0:-NAAF7J55JLNYQRY5gh1:bhdu5a4) ([raw file](https://github.com/coreumfoundation/faucet/blob/ca4b16a856586d92040c060f2fff99dc74e28814/main.go#L81)):*
> ```Go
> 	loggerConfig, loggerFlagRegistry := logger.ConfigureWithCLI(logger.ServiceDefaultConfig)
> 	log := logger.New(loggerConfig)
> 	ctx := logger.WithLogger(context.Background(), log)
> ```

IMO this looks strange logger.WithLogger
Shouldnt it be context.WithLogger returning ctx ?
___
*[`http/http.go` line 44 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/1#-N9fyPCz0SbgmRA0W0Wi:-NAAEnQIBv_4I99D7Gs_:briz2ww) ([raw file](https://github.com/coreumfoundation/faucet/blob/6245ba1ebfc35b9eb3b1c11d9c8ada6936cf2bc2/http/http.go#L44)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

we need to check if we can fix our code base easily then yes 
</blockquote></details>

ok for now
___
*[`http/http.go` line 48 at r14](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NAAEktCErr4Rm3_Pbze:-NAAEktCErr4Rm3_Pbzf:b-uawp78) ([raw file](https://github.com/coreumfoundation/faucet/blob/ca4b16a856586d92040c060f2fff99dc74e28814/http/http.go#L48)):*
> ```Go
> 
> // ErrorResponse is the response given in case an error occurred.
> type ErrorResponse struct {
> ```

not used anywhere replaced with APIError
___
*[`pkg/http/http.go` line 91 at r14](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NAAFd_27q-cQsv7OpaY:-NAAFd_27q-cQsv7OpaZ:b-quzjel) ([raw file](https://github.com/coreumfoundation/faucet/blob/ca4b16a856586d92040c060f2fff99dc74e28814/pkg/http/http.go#L91)):*
> ```Go
> 	}
> 	if forceShutdownTimeout == 0 {
> 		forceShutdownTimeout = 120 * time.Second
> ```

IMO 120 seconds is a bit too much

I usually put smth between 15-30s

![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/RtLwpGMMMk9Gabe4UJztYkjK/image.png)


<!-- Sent from Reviewable.io -->

2022-08-24 09:34 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 16 of 18 files reviewed, 9 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 81 at r14](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NAAF7J55JLNYQRY5gh0:-NAE5l8M8wuGgCIfgp3y:b5fhdem) ([raw file](https://github.com/coreumfoundation/faucet/blob/ca4b16a856586d92040c060f2fff99dc74e28814/main.go#L81)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO this looks strange logger.WithLogger
Shouldnt it be context.WithLogger returning ctx ?

</blockquote></details>

this syntax is used in logger package, I don't have a control over this. we can discuss it to update the logger package appropriately, and that is beyond the scope of this PR. 
___
*[`http/http.go` line 48 at r14](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NAAEktCErr4Rm3_Pbze:-NAE6YAEE9b4dTIfx5TR:ba3dfob) ([raw file](https://github.com/coreumfoundation/faucet/blob/ca4b16a856586d92040c060f2fff99dc74e28814/http/http.go#L48)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

not used anywhere replaced with APIError
</blockquote></details>

Removed
___
*[`pkg/http/http.go` line 91 at r14](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NAAFd_27q-cQsv7OpaY:-NAEBtTl83ZYPDfarJBH:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/ca4b16a856586d92040c060f2fff99dc74e28814/pkg/http/http.go#L91)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IMO 120 seconds is a bit too much

I usually put smth between 15-30s

![image.png](https://files.reviewableusercontent.io/images/reviewable/19859122/RtLwpGMMMk9Gabe4UJztYkjK/image.png)

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-24 09:38 UTC, ysv approved these changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: 16 of 18 files reviewed, 5 unresolved discussions (waiting on @wojtek-coreum, @xlab, and @ysv)

___
*[`main.go` line 81 at r14](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NAAF7J55JLNYQRY5gh0:-NAECa1b3ak3P_wF2rYF:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/ca4b16a856586d92040c060f2fff99dc74e28814/main.go#L81)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this syntax is used in logger package, I don't have a control over this. we can discuss it to update the logger package appropriately, and that is beyond the scope of this PR. 
</blockquote></details>

ok
___
*[`http/http.go` line 48 at r14](https://reviewable.io/reviews/coreumfoundation/faucet/1#-NAAEktCErr4Rm3_Pbze:-NAECgMZ7ERcIEX7GOPq:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/ca4b16a856586d92040c060f2fff99dc74e28814/http/http.go#L48)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Removed
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-08-24 10:31 UTC, wojtek-coreum approved these changes
> Reviewed 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 5 unresolved discussions (waiting on @xlab and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-24 12:37 UTC, wojtek-coreum approved these changes
> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/1)* status: all files reviewed, 5 unresolved discussions (waiting on @xlab and @ysv)



<!-- Sent from Reviewable.io -->

2022-08-24 13:47 UTC, merged