Handle concurrency and batch processing
CoreumFoundation/faucet pull request #11
Opened 2022-09-09 08:53 UTC by miladz68

2022-09-09 08:57 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch.go` line 134 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBWSixe1fc-1lyvb1u6:-NBWSixe1fc-1lyvb1u7:b-pnwnt1) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/client/coreum/batch.go#L134)):*
> ```Go
> 	fundingAddress := <-b.fundingAddressChan
> 	defer func() {
> 		b.fundingAddressChan <- fundingAddress
> ```

my only concern here is that code crashes for any reason, and this address does not get added back to the list. but in case of a crash here, the whole app will crash so it should be OK.


<!-- Sent from Reviewable.io -->

2022-09-09 10:18 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`main.go` line 82 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBWhiqS5t2_lVZBTDKm:-NBWhiqS5t2_lVZBTDKn:bn09u08) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/main.go#L82)):*
> ```Go
> 	}
> 	for _, addr := range addresses {
> 		fmt.Println(addr.String())
> ```

fmt.Println ?
___
*[`main.go` line 97 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBWi1wJ7PH0ctT1E7GK:-NBWi1wJ7PH0ctT1E7GL:b-1oq40v) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/main.go#L97)):*
> ```Go
> 		auth.AppModuleBasic{},
> 	)
> 	encodingConfig := cosmoscmd.MakeEncodingConfig(mbm)
> ```

Do you try to reduce the wasm import here, that's why you don't use the full modules struct?
___
*[`main.go` line 167 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBWifMi6yLOsqfeaceV:-NBWibfB1iMV2qxPVl3O:bjb935x) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/main.go#L167)):*
> ```Go
> }
> 
> func newKeyringFromFile(path string) (keyring.Keyring, []sdk.AccAddress, error) {
> ```

I see that, that change was done before, but why do we use the filepath instead mnemonic cli arg?



_Code quote:_
```Go
path
```
___
*[`client/coreum/batch.go` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBWjUpE9hoFxCk6Lurt:-NBWjUpE9hoFxCk6Luru:b-qsyazo) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/client/coreum/batch.go#L42)):*
> ```Go
> // coreumClient is the interface that provides Coreum coreumClient functionality
> type coreumClient interface {
> 	TransferTokenMany(
> ```

I would change the name, I don't like the "Many" here. How about "FundAccounts" quite standard name?
___
*[`client/coreum/batch.go` line 129 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBWjl9G4Y491M88wg-s:-NBWjl9G4Y491M88wg-t:bv40dgw) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/client/coreum/batch.go#L129)):*
> ```Go
> }
> 
> func (b *Batcher) batchSendRequests() {
> ```

To be honest, this code is overcomplicated. You need just to have a slice of messages and the ticker. So either the slice riches the threshold and you send messages, or ticker is executed. And also you need the mutex to lock send once you execute the batch, that's it. 
I understand that logic, but we can make it simplier. 


<!-- Sent from Reviewable.io -->

2022-09-09 11:56 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 0 of 8 files reviewed, 10 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX4FS3CamDzRptV1R1:-NBX4FS3CamDzRptV1R2:blk2ofd) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/app/app.go#L23)):*
> ```Go
> // New returns a new instance of the App
> func New(
> 	ctx context.Context,
> ```

You don't use the ctx
___
*[`client/coreum/batch.go` line 74 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX4M14BcZPSsmTi3CS:-NBX4M14BcZPSsmTi3CT:bty3kp3) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/client/coreum/batch.go#L74)):*
> ```Go
> 
> // TransferToken receives a singer transfer token request, batch sends them and returns the result
> func (b *Batcher) TransferToken(ctx context.Context, destAddress sdk.AccAddress) (string, error) {
> ```

You don't use the ctx here
___
*[`client/coreum/batch.go` line 115 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX4b9JDsO73s7f3bxl:-NBX4b9JDsO73s7f3bxm:b1dj0g3) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/client/coreum/batch.go#L115)):*
> ```Go
> // Start goroutine for batch processing requests
> func (b *Batcher) Start(ctx context.Context) {
> 	var exit bool
> ```

Why you need the exit here? It's always false
___
*[`client/coreum/batch.go` line 138 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX5BYWEUK1S98k5TO4:-NBX5BYWEUK1S98k5TO5:bmjnpjs) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/client/coreum/batch.go#L138)):*
> ```Go
> 	for {
> 		req := <-b.requestsChan
> 		// nil means channel is closed, all requests are processed, and we will not process any further requests
> ```

I would use the "req, ok := <-b.requestsChan" to see that the channel is closed. 


<!-- Sent from Reviewable.io -->

2022-09-09 11:58 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 0 of 8 files reviewed, 11 unresolved discussions (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch.go` line 55 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX6AgsBHfeTw7a_Ky-:-NBX6AgsBHfeTw7a_Ky0:b3zd0qw) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/client/coreum/batch.go#L55)):*
> ```Go
> 	logger             *zap.Logger
> 	client             coreumClient
> 	fundingAddressChan chan sdk.AccAddress
> ```

If you remove this channel start start using the routines the code will become sipler.


<!-- Sent from Reviewable.io -->

2022-09-09 12:03 UTC, ysv requested changes
I suggest to rename PR a bit to elaborate that it is about batching of bank send txs. 
Currently sounds too abstract

> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11#-:-NBX-zke8t6pud4hwt4u:bnmppg8)* status: 2 of 8 files reviewed, 14 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @wojtek-coreum)

___
*[`main.go` line 167 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBWifMi6yLOsqfeaceV:-NBX0jjr44Y94hKvN7UK:b2khuov) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/main.go#L167)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I see that, that change was done before, but why do we use the filepath instead mnemonic cli arg?
</blockquote></details>

Probably because we are going to have multiple faucet accounts. 
However I also prefer to use flags here with mnemonic or raw private key
___
*[`app/app.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX3kvM6v7ONrfJgVyA:-NBX3kvM6v7ONrfJgVyB:b-g4trsr) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/app/app.go#L23)):*
> ```Go
> // New returns a new instance of the App
> func New(
> 	ctx context.Context,
> ```

I don't really like when initialization func accepts ctx but here I don't see other way so I'm ok 
___
*[`app/app.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX43Ba8KXpwV9q7Goe:-NBX43Ba8KXpwV9q7Gof:b-9atkuv) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/app/app.go#L30)):*
> ```Go
> 	fundingAddresses []sdk.AccAddress,
> ) App {
> 	batcher := coreum.NewBatcher(ctx, logger, client, fundingAddresses, transferAmount)
> ```

Batcher doesn't need `ctx` in both places I think passing it to Start is enough
___
*[`client/coreum/batch.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX4KFZ9kbLQ9tTj9lD:-NBX4KFZ9kbLQ9tTj9lE:bb4utm) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/client/coreum/batch.go#L41)):*
> ```Go
> 
> // coreumClient is the interface that provides Coreum coreumClient functionality
> type coreumClient interface {
> ```

coredClient ?
___
*[`client/coreum/batch.go` line 42 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBWjUpE9hoFxCk6Lurt:-NBX4Ndm3xbinQJFwyGC:ba55ii4) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/client/coreum/batch.go#L42)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would change the name, I don't like the "Many" here. How about "FundAccounts" quite standard name?
</blockquote></details>

also don't like word 'many' here


<!-- Sent from Reviewable.io -->

2022-09-09 12:11 UTC, wojtek-coreum requested changes
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 3 of 8 files reviewed, 15 unresolved discussions (waiting on @dzmitryhil and @miladz68)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX90hI7MrDzVHo8w4N:-NBX90hI7MrDzVHo8w4O:bkuch08) (no related file):*
We had a design/pair-programming session and this code might eventually change. @miladz68 please ping me once you make your decision, then I will review.

___


<!-- Sent from Reviewable.io -->

2022-09-09 13:01 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 3 of 8 files reviewed, 15 unresolved discussions (waiting on @dzmitryhil and @miladz68)

___
*[`main.go` line 97 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBWi1wJ7PH0ctT1E7GK:-NBWsulg6q-xJp80371U:b2nhswy) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/main.go#L97)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Do you try to reduce the wasm import here, that's why you don't use the full modules struct?
</blockquote></details>

Yes
___
*[`main.go` line 167 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBWifMi6yLOsqfeaceV:-NBWsz7o-Y-Ee7C8YoB8:b-7pbor7) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/main.go#L167)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Probably because we are going to have multiple faucet accounts. 
However I also prefer to use flags here with mnemonic or raw private key
</blockquote></details>

it is simpler to put list of mnemonics in a file, if we are to import them via flags, and let's say we have 10 faucet accounts, the command line would be too large


<!-- Sent from Reviewable.io -->

2022-09-13 08:01 UTC, wojtek-coreum requested changes
For now I reviewed only the batcher. Will do the rest once discussions there are resolved.

> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11#-:-NBprR0oDp59X2gdHYRc:birupgu)* status: 5 of 9 files reviewed, 30 unresolved discussions (waiting on @dzmitryhil and @miladz68)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpgOO7ESfP71kkCmNW:-NBpgOO7ESfP71kkCmNX:b-ntxarx) (no related file):*
Non-blocking: I have to say that entire architecture of faucet (with http, app & batcher layers) is sooooo overcomplicated. I understand that we do it as an exercise for writing multi-layer applications. Could we assume that we can do it **if needed**?
Here the potential benefit of having reusable layers is of so low probability that I don't understand why we do that. Entire logic of faucet could be written in a single file using a few functions making everything 80% simpler.

___
___
*[`client/coreum/batch.go` line 23 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpfNFf6xQHzr20VbIY:-NBpfNFf6xQHzr20VbIZ:b4bldvh) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L23)):*
> ```Go
> 	amount sdk.Coin,
> ) *Batcher {
> 	requestBufferSize := 10 // number of requests that will be buffered to be batched
> ```

Those two variables should be passed via constructor
___
*[`client/coreum/batch.go` line 26 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpeLgo-pGQ4Tye7Mxr:-NBpeLgo-pGQ4Tye7Mxs:b-ynwbd0) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L26)):*
> ```Go
> 	batchSize := 10
> 	b := &Batcher{
> 		requestsChan:     make(chan request, requestBufferSize),
> ```

It doesn't make sense to define capacity on this channel. If processing requests is too slow, it doesn't matter if http requests are paused 10 requests earlier or later (when this buffer is full). The real solution in that situation is to provide more private keys. I can imagine that it would be useful to provide some prometheus metrics helping us to understand if faucet is congested or not. A good metric could be the number of "free" private keys (those who are ready to serve batch), if this number goes to 0 it means w e have a problem.
___
*[`client/coreum/batch.go` line 29 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpf9eM7AaqDHFNF0gm:-NBpf9eM7AaqDHFNF0gn:b-d91fws) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L29)):*
> ```Go
> 		logger:           logger,
> 		client:           client,
> 		fundingAddresses: append([]sdk.AccAddress{}, fundingAddresses...),
> ```

You could just assign it. This line does not provide any protection because each address is a byte slice so it still might be modified from both places.
___
*[`client/coreum/batch.go` line 32 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpfWeR79ankCuZT8kr:-NBpfWeR79ankCuZT8ks:b2ivpf5) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L32)):*
> ```Go
> 		amount:           amount,
> 		batchSize:        batchSize,
> 		mut:              &sync.RWMutex{},
> ```

Entire batcher is served through pointer, so pointer here is not needed
___
*[`client/coreum/batch.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpfeWfDXgHwjwpyXRM:-NBpfeWfDXgHwjwpyXRN:b-289xhh) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L33)):*
> ```Go
> 		batchSize:        batchSize,
> 		mut:              &sync.RWMutex{},
> 		stopped:          false,
> ```

This is not needed
___
*[`client/coreum/batch.go` line 52 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBphrI2-26NgaAtyY0S:-NBphrI2-26NgaAtyY0T:bdl9hnb) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L52)):*
> ```Go
> // Batcher exposes functionality to batch many transfer requests
> type Batcher struct {
> 	requestsChan     chan request
> ```

requestsChan -> requestChan
___
*[`client/coreum/batch.go` line 59 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpfo7VDMnnyyLUOKu0:-NBpfo7VDMnnyyLUOKu1:bxywle2) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L59)):*
> ```Go
> 	batchSize        int
> 
> 	mut     *sync.RWMutex
> ```

I think the common convention in go is to call it `mu`
___
*[`client/coreum/batch.go` line 73 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpg78h3wOMqCRigZjJ:-NBpg78h3wOMqCRigZjK:bews92w) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L73)):*
> ```Go
> }
> 
> // TransferToken receives a singer transfer token request, batch sends them and returns the result
> ```

singer -> single
___
*[`client/coreum/batch.go` line 74 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBphT4h0VSPB5wqprdq:-NBphT4h0VSPB5wqprdr:bvxozku) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L74)):*
> ```Go
> 
> // TransferToken receives a singer transfer token request, batch sends them and returns the result
> func (b *Batcher) TransferToken(ctx context.Context, destAddress sdk.AccAddress) (string, error) {
> ```

Couyld you rename it to sth like `EnqueueTokenTransferRequest` or sth similar? This method doesn't really transfer tokens.
___
*[`client/coreum/batch.go` line 98 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpj_5B0VLrD0jN_7mX:-NBpj_5C8BuzwbnSTfp3:bzhloym) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L98)):*
> ```Go
> }
> 
> func (b *Batcher) requestFund(address sdk.AccAddress) chan result {
> ```

should return `<-chan result`
___
*[`client/coreum/batch.go` line 104 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpi0KlEsUEwgzBW70W:-NBpi0Km0OQs3x0O3b0P:bgyt8bi) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L104)):*
> ```Go
> 	}
> 	if b.isClosed() {
> 		req.responseChan <- result{
> ```

Just return error from this function directly, it's much simpler to understand instead of following this indirection
___
*[`client/coreum/batch.go` line 115 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpl6XG1BYVkWW8du0Y:-NBpl6XH4hUOUPeRhBWW:b-4wv6il) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L115)):*
> ```Go
> // start starts goroutines for batch processing requests
> func (b *Batcher) start(ctx context.Context) {
> 	go func() {
> ```

This goroutine is a subject of race condition. The workflow of application (in `main.go`) is like this:
1. you start some goroutines here and there
2. in main goroutine you start http server
3. if signal is received you exit the http server (because of canceled context)
4. main goroutine exits
5. all the still-running goroutines are killed

And two scenarios might happen in the context of this particular goroutine:
1. If it catches canceled context too late, this goroutine (and all the others here) are just killed
2. If it's fast enough it eventually may process `b.close()` correctly

You may say  that it's not so important. My answer:
1. If it's not so important then remove it completely and let all the goroutines be killed (Bad approach)
2. If it is important then let's do it correctly (Good approach)

I'm saying it once again: please let's start handling goroutines correctly.  [...]

2022-09-14 06:41 UTC, wojtek-coreum requested changes
> Reviewed 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 5 of 9 files reviewed, 18 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch.go` line 23 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpfNFf6xQHzr20VbIY:-NBuiUue0HRgJNgJ0hkO:b-rxtzyl) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L23)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think so, the correct implementation would be to pass the max tx size and implement it in a way that the tx never exceeds that. but that is an over optimization. 
</blockquote></details>

They seem to be parameters controlling the behavior of batcher that's why I think it's a good idea to treat them like config
___
*[`client/coreum/batch.go` line 26 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpeLgo-pGQ4Tye7Mxr:-NBud82s0JoZeoss8-Yd:b7ffgym) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L26)):*
If there are two goroutines trying to add their items to the channel, the batcher will succeed immediately in both trials.

> but the other goroutine trying to write to it cannot react in time

this condition will never happens. If two goroutines are blocked by doing this:

```
someCh <- data
```

then the receiver in third goroutine will succeed with this:

```
data = <-someCh
data := <-someCh
```

immediately.
___
*[`client/coreum/batch.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpfeWfDXgHwjwpyXRM:-NBudvE4E7Xg0jglKGb9:b-n34gxi) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L33)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it is need to indicate we should accept any more incoming requests. 
</blockquote></details>

I mean setting it to `false` here is not needed
___
*[`client/coreum/batch.go` line 143 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpp5Cj6ps28jSOSIHw:-NBuem-yCKw1LMPO9n9Y:b-d7qk3i) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L143)):*
> I see no graceful way out of this

I see one :-)

> you may suggest to use parallel package

yes yes yes !

>  but I don't think that is the correct way of doing it

then propose whatever you think is better, but the code here creates a problem instead of fixing it. By doing it this way you create two issues:
- when application (http server) exits all the running goroutines are killed. It's not critical **in this particular** case but in general it's a bad practice - you don't power off your computer by unplugging it from the socket and/or removing battery.
- if previous issue is fixed (let's say) then in the next lines you force me to wait 20 seconds until application exits if node does not respond and I press ctrl+C to stop the application, because `ctx` passed there does not inherit the exit condition (signal).


... patiently waiting until team members are convinced to handle goroutines in better way ... :-)
___
*[`client/coreum/batch.go` line 150 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpppZJBFK_RA2lgEEt:-NBugeqsDbSyC_CA15tD:b54l7v3) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L150)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I prefer to return errors if there are network issues.
</blockquote></details>

But 90% of network issues are like 1-second blinks. Wouldn't world be more beautiful if software developers written their products in a way which makes users' life easier, not harder?
___
*[`client/coreum/batch.go` line 165 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpoHgO7UP7Qllyba-0:-NBuh0Ti-Oid7MsEp4pj:b4zcd6l) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L165)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

If I understood your concern correctly, I check if there are more items in the channel and it there are not, then batch that request on its own.
</blockquote></details>

It doesn't work this way. channel returns `ok == false` only once channel is closed. If it's open but there are no items it patiently waits for the next one.
___
*[`client/coreum/batch.go` line 167 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpns3HDKvMyhMGxXN5:-NBuhTBH-qOV3j9jwptr:bh8cif0) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L167)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

because in case that the channel is close and there are some message in current batch, those must be dispatched.
</blockquote></details>

But if channel is closed, it means that application exits right? Do we care about requests added to the batch? If yes, then why don't we care about those waiting in `requestChan` or even in open http requests? Are the first ones just more lucky? It adds additional delay to the application shutdown because faucet must wait until block is committed.
When faucet exits some http requests will fail this or that way, so I don't see much value in giving more attention to those lucky ones which transitioned from one buffer to another.


<!-- Sent from Reviewable.io -->

2022-09-14 08:45 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 5 of 9 files reviewed, 18 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch.go` line 23 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpfNFf6xQHzr20VbIY:-NButHa91PTkE5RG-a6x:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

They seem to be parameters controlling the behavior of batcher that's why I think it's a good idea to treat them like config
</blockquote></details>

Done.
___
*[`client/coreum/batch.go` line 26 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpeLgo-pGQ4Tye7Mxr:-NBv3dzFDh8nY9VUr1vE:b-fu81t6) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L26)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If there are two goroutines trying to add their items to the channel, the batcher will succeed immediately in both trials.

> but the other goroutine trying to write to it cannot react in time

this condition will never happens. If two goroutines are blocked by doing this:

```
someCh <- data
```

then the receiver in third goroutine will succeed with this:

```
data = <-someCh
data := <-someCh
```

immediately.
</blockquote></details>

it is not immedite, since goroutines go to sleep if they are blocked and are not guaranteed to come back online immediate after there room in the channel to write to. 
I wrote a test to show case it, please take a look, if we make the channel unbuffered some batches will have a smaller size.
___
*[`client/coreum/batch.go` line 33 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpfeWfDXgHwjwpyXRM:-NBv4D1G8fDXXAo3QDmO:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L33)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I mean setting it to `false` here is not needed
</blockquote></details>

Done.
___
*[`client/coreum/batch.go` line 115 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpl6XG1BYVkWW8du0Y:-NBv5BR-CPZ29pwgRZd5:b-fzesm7) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L115)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This goroutine is a subject of race condition. The workflow of application (in `main.go`) is like this:
1. you start some goroutines here and there
2. in main goroutine you start http server
3. if signal is received you exit the http server (because of canceled context)
4. main goroutine exits
5. all the still-running goroutines are killed

And two scenarios might happen in the context of this particular goroutine:
1. If it catches canceled context too late, this goroutine (and all the others here) are just killed
2. If it's fast enough it eventually may process `b.close()` correctly

You may say  that it's not so important. My answer:
1. If it's not so important then remove it completely and let all the goroutines be killed (Bad approach)
2. If it is important then let's do it correctly (Good approach)

I'm saying it once again: please let's start handling goroutines correctly. Using `go` keyword is not the right way of managing goroutines.
</blockquote></details>

We are having these discussions too often with the agenda to introduce the parallel package, which I am not the sole decider on. 

The parallel package suffers from same pitfalls as you mention as well and makes the architecture of the application very ugly as we have seen in the crust package. It encourages all the code be in the same place and does not allow for a proper separation of concerns. However I agree that it makes concurrency simpler to reason about but it makes the architecture of the code worse. 

Regarding the proper shutdown mechanism, we can spend time to get it right (the parallel package does not get it right IMO as we have discussed before) but it is a question of resources(man power), do we want to spend months on the faucet ? we have already made a much better version than the faucet in the cosmos repo and it is already an overkill IMO.

But regarding your point, it is not a race between http and bacther to close and exit go routines, because http server will wait for all handlers to exit, which will happen if all channels are emptied out and closed.  

So this a question to the team 
@ysv @dzmitryhil 
Should we spend time to handle graceful shutdown in a better way.
___
*[`client/coreum/batch.go` line 143 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpp5Cj6ps28jSOSIHw:-NBv4JI90IU1bAP5jwiq:b-z2yw6s) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L143)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

> I see no graceful way out of this

I see one :-)

> you may suggest to use parallel package

yes yes yes !

>  but I don't think that is the correct way of doing it

then propose whatever you think is better, but the code here creates a problem instead of fixing it. By doing it this way you create two issues:
- when application (http server) exits all the running goroutines are killed. It's not critical **in this particular** case but in general it's a bad practice - you don't power off your computer by unplugging it from the socket and/or removing battery.
- if previous issue is fixed (let's say) then in the next lines you force me to wait 20 seconds until application exits if node does not respond and I press ctrl+C to stop the application, because `ctx` passed there does not inherit the exit condition (signal).


... patiently waiting until team members are convinced to handle goroutines in better way ... :-)

</blockquote></details>

ok, let's wait for the team to agree, in the mean time let's have this resolved.
___
*[`client/coreum/batch.go` line 150 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpppZJBFK_RA2lgEEt:-NBv4Xf1Ctg0N6YdHgGq:brdhcm5) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L150)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But 90% of network issues are like 1-second blinks. Wouldn't world be more beautiful if software developers written their products in a way which makes users' life easier, not harder?
</blockquote></details>

@ysv @dzmitryhil 
Do you think we need to have retrials here ?
___
*[`client/coreum/batch.go` line 165 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpoHgO7UP7Qllyba-0:-NBv4gpO2qbC2INGp6RI:b3sro6y) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L165)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It doesn't work this way. channel returns `ok == false` only once channel is closed. If it's open but there are no items it patiently waits for the next one.
</blockquote></details>

I understand your point, when I say there is an if statement, I mean at the end of the for loop. 
___
*[`client/coreum/batch.go` line 167 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpns3HDKvMyhMGxXN5:-NBv4sp8AVIe-KccLXQ7:bclugwz) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L167)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But if channel is closed, it means that applica [...]

2022-09-14 09:39 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 5 of 9 files reviewed, 15 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvLlvp7A_V4tacO7VS:-NBvLlvp7A_V4tacO7VT:bchzybh) (no related file):*
There is one general concern I would like to discuss:
If faucet is requested to terminate it still tries to serve all the enqueued and open requests. It means that in the worst case (when there are notwork issues) it might take ~20 seconds (timeout) to close it. It might be inconvenient if someone is testing it manually or cause some delays when app runs in docker/kubernetes. I would prefer to just abandon all the pending requests and exit immediately. WDYT?

___
___
*[`client/coreum/batch.go` line 115 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpl6XG1BYVkWW8du0Y:-NBvIkqbCVWLM2O2ujA5:b-tamxb4) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L115)):*
> It encourages all the code be in the same place and does not allow for a proper separation of concerns

This is not true. The fact that I usually do it this way in simple cases is my personal preference, not the requirement.

> because http server will wait for all handlers to exit, which will happen if all channels are emptied out and closed

Okay, I see it now. Because http request doesn't exit immediately, it still waits for tx to be processed. I think there is no need to wait until enqueued requests are served, but it's entire topic.
___
*[`client/coreum/batch.go` line 165 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpoHgO7UP7Qllyba-0:-NBvLMjOE0B_gPouuz2H:bdl20xg) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L165)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I understand your point, when I say there is an if statement, I mean at the end of the for loop. 
</blockquote></details>

Ok, now I understand
___
*[`client/coreum/batch.go` line 167 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpns3HDKvMyhMGxXN5:-NBvLY-YCFoW_LoEYkor:b68jat9) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L167)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we do care about the requests on requestChan and do care about open http requests, we wait for http requests to finish and process all request in the requestChan before closing it. 
</blockquote></details>

ok, I see now


<!-- Sent from Reviewable.io -->

2022-09-14 09:52 UTC, wojtek-coreum requested changes
> Reviewed 1 of 8 files at r1, 1 of 4 files at r2, 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 17 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`main.go` line 183 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvNYY_ARdBFrM8Eu3D:-NBvNYY_ARdBFrM8Eu3E:bxxn7cb) ([raw file](https://github.com/coreumfoundation/faucet/blob/2ab0d2ac901b72f73a49e003f8aadc90c1335394/main.go#L183)):*
> ```Go
> 	for scanner.Scan() {
> 		mnemonic := scanner.Text()
> 		tempKr := keyring.NewInMemory()
> ```

why two keyrings are used?
___
*[`app/app.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX4FS3CamDzRptV1R1:-NBvON7lAoZU-mBLd3cJ:b-batuq5) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/app/app.go#L23)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

refactored the code, I need it now.
</blockquote></details>

As mentioned in another comment, if `start` is exported then ctx is not needed here
___
*[`client/coreum/batch.go` line 35 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvNqAuCr0zoSp-2oks:-NBvNqAuCr0zoSp-2okt:btypcpb) ([raw file](https://github.com/coreumfoundation/faucet/blob/2ab0d2ac901b72f73a49e003f8aadc90c1335394/client/coreum/batch.go#L35)):*
> ```Go
> 		stopped:          false,
> 	}
> 	b.start(ctx)
> ```

IMO, `start` should be exported and called directly. It is unexpected that constructors do sth more (use resources, start sth, execute business logic) than just creating an object.
Sth like this:

```go
batcher := batcher.New(...) // <- no ctx passed here
batcher.Start(ctx)
```


<!-- Sent from Reviewable.io -->

2022-09-14 09:58 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 17 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`main.go` line 183 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvNYY_ARdBFrM8Eu3D:-NBvPWaK6JvdikAMXJ8S:b-ze95o9) ([raw file](https://github.com/coreumfoundation/faucet/blob/2ab0d2ac901b72f73a49e003f8aadc90c1335394/main.go#L183)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why two keyrings are used?
</blockquote></details>

one is used to get the account address first to be later used that key name on the main keyring
___
*[`app/app.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX4FS3CamDzRptV1R1:-NBvQwaR20-ROst8TqFQ:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/app/app.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

As mentioned in another comment, if `start` is exported then ctx is not needed here
</blockquote></details>

Done.
___
*[`client/coreum/batch.go` line 35 at r3](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvNqAuCr0zoSp-2oks:-NBvQRbR4HS2Cp6TFeFO:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/2ab0d2ac901b72f73a49e003f8aadc90c1335394/client/coreum/batch.go#L35)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

IMO, `start` should be exported and called directly. It is unexpected that constructors do sth more (use resources, start sth, execute business logic) than just creating an object.
Sth like this:

```go
batcher := batcher.New(...) // <- no ctx passed here
batcher.Start(ctx)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-14 10:01 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 17 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvLlvp7A_V4tacO7VS:-NBvRSSNEcj1C9gRMl93:b-8wb3tv) (no related file):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

There is one general concern I would like to discuss:
If faucet is requested to terminate it still tries to serve all the enqueued and open requests. It means that in the worst case (when there are notwork issues) it might take ~20 seconds (timeout) to close it. It might be inconvenient if someone is testing it manually or cause some delays when app runs in docker/kubernetes. I would prefer to just abandon all the pending requests and exit immediately. WDYT?
</blockquote></details>

@ysv @dzmitryhil 

___


<!-- Sent from Reviewable.io -->

2022-09-14 10:43 UTC, wojtek-coreum requested changes
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 9 of 10 files reviewed, 20 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX4FS3CamDzRptV1R1:-NBvYULZ0Nihs3po3TqD:b-tdjwpf) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/app/app.go#L23)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But it's still here
___
*[`app/app.go` line 31 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvYarP8ZKccY4cgdu1:-NBvYarP8ZKccY4cgdu2:brf84v1) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/app/app.go#L31)):*
> ```Go
> ) App {
> 	batcher := coreum.NewBatcher(logger, client, fundingAddresses, transferAmount, 10)
> 	batcher.Start(ctx)
> ```

Again, doing this in a constructor is a bad idea.
There are two options:
1. create batcher outside the app and start it from there
2. add `Start` method to the app
___
*[`client/coreum/batch.go` line 123 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvZIMK1DC9s-8UL5K4:-NBvZIMLC_M0DQzYwPEk:bdw76au) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch.go#L123)):*
> ```Go
> 		b.close()
> 	}()
> 	go func() {
> ```

```go
go b.createBatches()
```
___
*[`client/coreum/batch.go` line 172 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBv_34R2B-NWNJhfI-x:-NBv_34R2B-NWNJhfI-y:b680qb6) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch.go#L172)):*
> ```Go
> 			exit = true
> 		} else {
> 			ba.addresses = append(ba.addresses, req.address)
> ```

Is there a value in doing it this way instead of defining `ba := make([]request, 0, batchSize)`?
___
*[`client/coreum/batch_test.go` line 14 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvaAQ3-hUbT5qwsqZc:-NBvaAQ3-hUbT5qwsqZd:b-o5hqvf) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch_test.go#L14)):*
> ```Go
> )
> 
> func TestBatchSize(t *testing.T) {
> ```

what about testing second part of batcher - sending batch to client?
___
*[`client/coreum/batch_test.go` line 32 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBv_hkn5gQZGPqQG8Bv:-NBv_hkn5gQZGPqQG8Bw:bzf8ia6) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch_test.go#L32)):*
> ```Go
> 		go func() { batcher.requestChan <- request{} }()
> 	}
> 	time.Sleep(10 * time.Millisecond)
> ```

You don't need this. You may do `batcher.requestChan <- request{}` 10 times in the same goroutine and then wait on `batch, ok := <-batcher.batchChan`, at appropriate time you will get result there
___
*[`client/coreum/batch_test.go` line 36 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBva84x9PYL3nhNeY1B:-NBva84x9PYL3nhNeY1C:bxjyf1r) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch_test.go#L36)):*
> ```Go
> 	batcher.Start(ctx)
> 
> 	batch, ok := <-batcher.batchChan
> ```

it needs a timeout


<!-- Sent from Reviewable.io -->

2022-09-14 10:53 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 9 of 10 files reviewed, 23 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch.go` line 25 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBva_lb55MDqHqHAbp-:-NBva_lb55MDqHqHAbp0:b-axylka) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch.go#L25)):*
> ```Go
> 	requestBufferSize := batchSize // number of requests that will be buffered to be batched
> 	b := &Batcher{
> 		requestChan:      make(chan request, requestBufferSize),
> ```

it seems reasonable to use `batchSize` directly here because to build a batch you accept this number of requests in maximum
___
*[`client/coreum/batch.go` line 30 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvaqJL9lxAPVId6nZg:-NBvaqJM1L2Vg0B8K5ds:b-v4q0fl) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch.go#L30)):*
> ```Go
> 		fundingAddresses: append([]sdk.AccAddress{}, fundingAddresses...),
> 		amount:           amount,
> 		batchSize:        batchSize,
> ```

there is one place where you use this field and it might be replaced with `cap(b.requestChan)`, it might be better to rename `requestChan` to sth like `bufferChan`.
___
*[`client/coreum/batch.go` line 146 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvb_wyCj3RpDoxD-mm:-NBvb_wyCj3RpDoxD-mn:bmryty0) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch.go#L146)):*
> ```Go
> 		}
> 
> 		ctx := logger.WithLogger(context.Background(), b.logger)
> ```

Some time ago my colleague wrote this wrapper for this purpose: 

```go
package tcontext

import (
	"context"

	"go.tectonic.network/lib/time"
)

// Reopen returns a context that inherits all the values stored in the given
// parent context, but not tied to the parent's lifespan. The returned context
// has no deadline.
//
// Reopen can even be used on an already closed context, hence the name.
func Reopen(ctx context.Context) context.Context {
	return reopened{Context: ctx}
}

type reopened struct {
	context.Context // nolint:containedctx // this struct exists to wrap a context
}

func (reopened) Deadline() (time.Time, bool) {
	return time.Time{}, false
}

func (reopened) Done() <-chan struct{} {
	return nil
}

func (reopened) Err() error {
	return nil
}
```

by using it, you may accept normal ctx (canceled by signal) as an argument to the function and simplify this and the next line to:

```go
ctx, cancel := context.WithTimeout(tcontext.Reopen(ctx), 20*time.Second)
```

so you don't need to inject logger again.
It's a common scenario where ctx cancellation caused by signal must be ignored during shutdown but still keeping values stored inside ctx. That's the part of my arguments that `context.Background` should be called only once in the app when root `ctx` is created.


<!-- Sent from Reviewable.io -->

2022-09-14 10:58 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 9 of 10 files reviewed, 26 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch.go` line 76 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvcu8BE06-wceJrr3Z:-NBvcu8BE06-wceJrr3_:b-5f8mzl) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch.go#L76)):*
> ```Go
> 	resChan, err := b.requestFund(destAddress)
> 	if err != nil {
> 		return "", errors.WithStack(err)
> ```

`WithStack` is not needed here
___
*[`client/coreum/batch.go` line 79 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvdHlE2N6ci24yPabV:-NBvdHlE2N6ci24yPabW:b-bx2lz7) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch.go#L79)):*
> ```Go
> 	}
> 	select {
> 	case <-ctx.Done():
> ```

Because of this, in case of faucet termination, this function will exit without handling the request. It means two things at the moment:
1. faucet does not really care about ongoing requests
2. race condition I described in `close` might happen because of this
___
*[`client/coreum/batch.go` line 80 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvd0PM5XrjHMn6od7f:-NBvd0PM5XrjHMn6od7g:b-u1azc) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch.go#L80)):*
> ```Go
> 	select {
> 	case <-ctx.Done():
> 		return "", errors.New("request aborted")
> ```

`errors.Wrap(ctx.Err(), ...)`


<!-- Sent from Reviewable.io -->

2022-09-14 11:05 UTC, wojtek-coreum requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 9 of 10 files reviewed, 27 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch.go` line 177 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvevor0TbB38lg0i72:-NBvevor0TbB38lg0i73:b-gpb45) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch.go#L177)):*
> ```Go
> 
> 		if len(ba.addresses) >= b.batchSize || len(b.requestChan) == 0 || exit {
> 			b.batchChan <- ba
> ```

this should happen only if `len(ba) > 0`, otherwise it's possible that when exit is true, empty tx is generated


<!-- Sent from Reviewable.io -->

2022-09-14 12:49 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 9 of 10 files reviewed, 21 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvLlvp7A_V4tacO7VS:-NBw1YSPDQ546ZwBS3vG:b-o6rzn1) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@ysv @dzmitryhil 
</blockquote></details>

If you test it locally, it's had to face such issue. I prefer to have graceful shutdown rather exit.

___


<!-- Sent from Reviewable.io -->

2022-09-15 05:59 UTC, wojtek-coreum requested changes
> Reviewed 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 9 of 10 files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX4FS3CamDzRptV1R1:-NBzfv0ABEs_Y2TPegY6:b-dfrx2z) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/app/app.go#L23)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

well ctx is passed to the app and app calls the start and passes it to start.
</blockquote></details>

Now it doesn't so `ctx` may be removed
___
*[`app/app.go` line 24 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBzikiXC_-461G5pq5k:-NBzikiXC_-461G5pq5l:b-gnw0xi) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/app/app.go#L24)):*
> ```Go
> func New(
> 	ctx context.Context,
> 	logger *zap.Logger,
> ```

`logger` is not used anymore too
___
*[`app/app.go` line 25 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBzdsi6Dx7R1_eUlmN0:-NBzdsi6Dx7R1_eUlmN1:be5t9dq) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/app/app.go#L25)):*
> ```Go
> 	ctx context.Context,
> 	logger *zap.Logger,
> 	batcher *coreum.Batcher,
> ```

Minor (I don't care much): It would be nice to not pass full `*coreum.Batcher` here but only an interface exposing required method
___
*[`client/coreum/batch.go` line 150 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpppZJBFK_RA2lgEEt:-NBzg-oS7dCV_sD8YWNy:b-omglzn) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L150)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

@ysv @dzmitryhil 
Do you think we need to have retrials here ?
</blockquote></details>

We decided to support graceful shutdown to be nice to the users. Then retrying on network hiccups is even more important because they will happen more often than faucet restarts.
___
*[`client/coreum/batch.go` line 172 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBv_34R2B-NWNJhfI-x:-NBzey6h4cuZkefGmyNw:b-5hqwge) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch.go#L172)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't understand the question
</blockquote></details>

Current state:

- `request` type holding request info
- `batch` type holding slices, each slice being responsible for collecting information from `request`s - just in separate slices

My idea:

define ` type batch []request` and add requests there directly instead of reassigning each field to separate slice
___
*[`client/coreum/batch.go` line 25 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBzeAPr1ZzWM53ubC3a:-NBzeAPr1ZzWM53ubC3b:b-tzvvzd) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L25)):*
> ```Go
> 	requestBufferSize := batchSize // number of requests that will be buffered to be batched
> 	b := &Batcher{
> 		requestsBuffer:   make(chan request, requestBufferSize),
> ```

requestsBuffer -> requestBuffer
___
*[`client/coreum/batch.go` line 120 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBzhm-Q9f917cjVuIxV:-NBzhm-R29CI6gzhWpTE:bdr6rxe) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L120)):*
> ```Go
> 	for _, fundingAddress := range b.fundingAddresses {
> 		go func(addr sdk.AccAddress) {
> 			b.processBatches(addr)
> ```

This function uses `b.logger` but `Start` already receives `ctx` containing the logger, so it's better to
- retrieve it from here and pass as a parameter to `b.processBatches`
- or even pass entire `ctx` there and retrieve logger there
- or, in a consequence of previous point, use `Reopen` function I proposed earlier to avoid dancing with different contexts at all

After implementing one of those options `b.logger` might be removed.
___
*[`client/coreum/batch_test.go` line 32 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBv_hkn5gQZGPqQG8Bv:-NBzfjxe-x8GiSVT-AZV:b-b6ud1r) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch_test.go#L32)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the update
___
*[`client/coreum/batch_test.go` line 31 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBzfoCg4I4z4PqAbkKZ:-NBzfoCg4I4z4PqAbkK_:b8vel6e) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch_test.go#L31)):*
> ```Go
> 	go func() {
> 		for i := 0; i < 10; i++ {
> 			batcher.requestsBuffer <- request{}
> ```

it also needs a timeout


<!-- Sent from Reviewable.io -->

2022-09-15 07:53 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 9 of 10 files reviewed, 17 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch.go` line 28 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-5ymSAk6kkhvdBFTG:-NC-5ymSAk6kkhvdBFTH:btj39jf) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L28)):*
> ```Go
> 		logger:           logger,
> 		client:           client,
> 		fundingAddresses: append([]sdk.AccAddress{}, fundingAddresses...),
> ```

Why do you need this? Why don't you just set the input slice?
___
*[`client/coreum/batch.go` line 73 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-50TL1HbkP3ulreMr:-NC-50TL1HbkP3ulreMs:bty3kp3) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L73)):*
> ```Go
> 
> // TransferToken receives a single transfer token request, batch sends them and returns the result
> func (b *Batcher) TransferToken(ctx context.Context, destAddress sdk.AccAddress) (string, error) {
> ```

You don't use the ctx here
___
*[`client/coreum/batch.go` line 103 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-57Jb1dSOXKMqGCbA:-NC-57Jb1dSOXKMqGCbB:b9kbjvk) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L103)):*
> ```Go
> 		address:      address,
> 	}
> 	if b.isClosed() {
> ```

Logicaly it's better to do in the first lines of the method
___
*[`client/coreum/batch.go` line 139 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-5Vw2-OObBKnfq9XO:-NC-5Vw2-OObBKnfq9XP:bai0j0a) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L139)):*
> ```Go
> 		ctx := logger.WithLogger(context.Background(), b.logger)
> 		ctx, cancel := context.WithTimeout(ctx, 20*time.Second)
> 		defer cancel()
> ```

The defer will be called at the end of the "processBatch" not at the end of the for. That might cause the reourses leak. 
___
*[`client/coreum/batch.go` line 161 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-6b1P8RItZoUsN7iF:-NC-6b1P8RItZoUsN7iG:b-kmn6am) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L161)):*
> ```Go
> 		req, ok := <-b.requestsBuffer
> 		if !ok {
> 			exit = true
> ```

Instead of keeping the "var exit bool" flag you can you the "ok" in the " len(b.requestsBuffer) == 0 || exit)" and break loop at the end.  


<!-- Sent from Reviewable.io -->

2022-09-15 08:38 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 9 of 10 files reviewed, 16 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`app/app.go` line 23 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX4FS3CamDzRptV1R1:-NC-9_ZGAjPFHB-w9tct:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/app/app.go#L23)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Now it doesn't so `ctx` may be removed
</blockquote></details>

Done.
___
*[`app/app.go` line 24 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBzikiXC_-461G5pq5k:-NC-9f8K0JgjsMWjLXkL:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/app/app.go#L24)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`logger` is not used anymore too
</blockquote></details>

Done.
___
*[`client/coreum/batch.go` line 172 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBv_34R2B-NWNJhfI-x:-NC-EvaJ2_R345xaKZxK:b-c86z6f) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch.go#L172)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Current state:

- `request` type holding request info
- `batch` type holding slices, each slice being responsible for collecting information from `request`s - just in separate slices

My idea:

define ` type batch []request` and add requests there directly instead of reassigning each field to separate slice
</blockquote></details>

in that case we will need to do another loop to create a list of addresses to pass that list to the SendToken function and another loop to send responses. In other words those 2 lists are consumed independently.
___
*[`client/coreum/batch.go` line 25 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBzeAPr1ZzWM53ubC3a:-NC-ARWa0vQ5KHVi-Lb0:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L25)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

requestsBuffer -> requestBuffer
</blockquote></details>

Done.
___
*[`client/coreum/batch.go` line 28 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-5ymSAk6kkhvdBFTG:-NC-Aedv3uoyqHdE52cy:b-qbm08r) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L28)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why do you need this? Why don't you just set the input slice?
</blockquote></details>

wojtek had a similar comment, removed.
___
*[`client/coreum/batch.go` line 73 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-50TL1HbkP3ulreMr:-NC-Al__6XHFlHd29jyv:b3wrsfm) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L73)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

You don't use the ctx here
</blockquote></details>

that is fine.
___
*[`client/coreum/batch.go` line 103 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-57Jb1dSOXKMqGCbA:-NC-B-Ni8iImjFy3MC17:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L103)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Logicaly it's better to do in the first lines of the method
</blockquote></details>

Done.
___
*[`client/coreum/batch.go` line 120 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBzhm-Q9f917cjVuIxV:-NC-BLBW8fCu36LA5ZKL:bt8umtm) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This function uses `b.logger` but `Start` already receives `ctx` containing the logger, so it's better to
- retrieve it from here and pass as a parameter to `b.processBatches`
- or even pass entire `ctx` there and retrieve logger there
- or, in a consequence of previous point, use `Reopen` function I proposed earlier to avoid dancing with different contexts at all

After implementing one of those options `b.logger` might be removed.
</blockquote></details>

I hate this approach to wrap objects in ctx and unwrap in other places
___
*[`client/coreum/batch.go` line 139 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-5Vw2-OObBKnfq9XO:-NC-EHl-9dWDWoeVpLJb:b-7yw8mk) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L139)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The defer will be called at the end of the "processBatch" not at the end of the for. That might cause the reourses leak. 
</blockquote></details>

excellent catch, fixed
___
*[`client/coreum/batch.go` line 161 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-6b1P8RItZoUsN7iF:-NC-Erhc1sGLgNQqSd8i:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L161)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Instead of keeping the "var exit bool" flag you can you the "ok" in the " len(b.requestsBuffer) == 0 || exit)" and break loop at the end.  
</blockquote></details>

Done.
___
*[`client/coreum/batch_test.go` line 32 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBv_hkn5gQZGPqQG8Bv:-NC-Fyrd55Cxi6mnREYo:b-le6cau) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch_test.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

I don't see the update
</blockquote></details>

it is a single goroutine instead of 10, that's how I understood your comment
___
*[`client/coreum/batch_test.go` line 31 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBzfoCg4I4z4PqAbkKZ:-NC-FsOO3PFqQdUVWAQ9:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch_test.go#L31)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

it also needs a timeout
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-15 09:23 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 6 of 10 files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch.go` line 73 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-50TL1HbkP3ulreMr:-NC-RxpH5yeR1uZRdSCS:bkikle1) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L73)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

that is fine.
</blockquote></details>

Why it's fine? If you don't use that variable and you don't have to follow the interface contract, then remove it. 


<!-- Sent from Reviewable.io -->

2022-09-15 10:06 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 5 of 10 files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch.go` line 73 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-50TL1HbkP3ulreMr:-NC-ar1986lkmWJ9WQb3:b5gieyx) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L73)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Why it's fine? If you don't use that variable and you don't have to follow the interface contract, then remove it. 
</blockquote></details>

I did think about this a bit more and I think you are correct, wojtek had left a comment that if the abort this request if ctx if Done that means we do not respect finishing all requests. but when I think more this context will not be cancelled when a graceful shutdown is initiated. 
Fixed to respect the ctx.
___
*[`client/coreum/batch_test.go` line 14 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvaAQ3-hUbT5qwsqZc:-NC-_PFx8NeRL9lMZG3k:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch_test.go#L14)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

what about testing second part of batcher - sending batch to client?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-15 12:04 UTC, wojtek-coreum requested changes
> Reviewed 2 of 4 files at r6, 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 17 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`client/coreum/batch.go` line 73 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-50TL1HbkP3ulreMr:-NC-x9ZK8VQNk0zjLraM:b-d7bbgn) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L73)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I did think about this a bit more and I think you are correct, wojtek had left a comment that if the abort this request if ctx if Done that means we do not respect finishing all requests. but when I think more this context will not be cancelled when a graceful shutdown is initiated. 
Fixed to respect the ctx.
</blockquote></details>

When is this context canceled then?
___
*[`client/coreum/batch.go` line 120 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBzhm-Q9f917cjVuIxV:-NC-xHEjBpxCf2vQeMOy:bnnwpqg) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L120)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I hate this approach to wrap objects in ctx and unwrap in other places
</blockquote></details>

But we all had a discussion when we agreed that logger is handled inside ctx. Now you pass logger twice, once in constructor, second time in `ctx` here. 
___
*[`client/coreum/batch.go` line 135 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-xpUKADf83KgOrZGY:-NC-xpUKADf83KgOrZGZ:b2fpibb) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch.go#L135)):*
> ```Go
> 
> func (b *Batcher) processBatches(fromAddress sdk.AccAddress) {
> 	b.logger.Debug("processBatches started", zap.Stringer("fromAddress", fromAddress))
> ```

Non-blocking: this reinvents a framework which logs startup and exit of every goroutine in the app in consistent way. Now you have goroutines which log it and others which don't. Why is this one special? Two suggestions:
- be consistent and log it everywhere then
- let's use a framework which does not require everyone to even think about repeatable tasks
___
*[`client/coreum/batch.go` line 144 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-yaz420BFJwOYIEdp:-NC-yaz420BFJwOYIEdq:b5kh2n9) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch.go#L144)):*
> ```Go
> 		b.sendBatch(fromAddress, ba)
> 	}
> 	b.logger.Debug("processBatches exit", zap.Stringer("fromAddress", fromAddress))
> ```

Do it inside `defer` at the beginning so it is logged even if code panics. Or even create a special case with `recover` logging the panic (reinventing the wheel again)
___
*[`client/coreum/batch_test.go` line 32 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBv_hkn5gQZGPqQG8Bv:-NC-z76c83ZGO96l14Vw:bfwd9lu) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch_test.go#L32)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it is a single goroutine instead of 10, that's how I understood your comment
</blockquote></details>

My comment was about the fact that you don't need a goroutine at all
___
*[`client/coreum/batch_test.go` line 15 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC011CGBBV-JjfcIjne:-NC011CGBBV-JjfcIjnf:b-nysymn) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L15)):*
> ```Go
> )
> 
> func TestBatchSize(t *testing.T) {
> ```

It seems to me that the second test tests everything end-to-end so maybe this one is not needed
___
*[`client/coreum/batch_test.go` line 19 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-zbTnCv3yaAwotiel:-NC-zbTnCv3yaAwotiem:bke3b3e) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L19)):*
> ```Go
> 	log := zaptest.NewLogger(t)
> 	ctx, cancel := context.WithCancel(context.Background())
> 	defer cancel()
> ```

`t.Cleanup(cancel)`
___
*[`client/coreum/batch_test.go` line 34 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-zEz2Aa37v6UY3Wv2:-NC-zEz2Aa37v6UY3Wv3:bj91m2r) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L34)):*
> ```Go
> 			select {
> 			case batcher.requestBuffer <- request{}:
> 			case <-time.After(time.Second):
> ```

return an error in this case because it means that code didn't work as expected, because all the 10 requests should be placed inside buffer immediately
___
*[`client/coreum/batch_test.go` line 52 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0-b4l5zfU4Ug_a2dX:-NC0-b4l5zfU4Ug_a2dY:b-fb3039) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L52)):*
> ```Go
> 
> type mockCoreumClient struct {
> 	calls []clientCall
> ```

This must be protected by mutex
___
*[`client/coreum/batch_test.go` line 79 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-zXdq4jjnOYqGDHSy:-NC-zXdq4jjnOYqGDHSz:bke3b3e) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L79)):*
> ```Go
> 	log := zaptest.NewLogger(t)
> 	ctx, cancel := context.WithCancel(context.Background())
> 	defer cancel()
> ```

`t.Cleanup(cancel)`
___
*[`client/coreum/batch_test.go` line 88 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-zslr2lvSXY8ikMFq:-NC-zslr2lvSXY8ikMFr:b78a8p2) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L88)):*
> ```Go
> 
> 	mock := &mockCoreumClient{}
> 	batcher := *NewBatcher(log, mock, fundingAddresses, amount, 10)
> ```

why `*`?
___
*[`client/coreum/batch_test.go` line 95 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC00k_aDYzEASvfhdD4:-NC00k_aDYzEASvfhdD5:b-uje89h) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L95)):*
> ```Go
> 		wg.Add(1)
> 		go func() {
> 			_, _ = batcher.TransferToken(ctx, nil)
> ```

Responses should be collected and verified
___
*[`client/coreum/batch_test.go` line 102 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0017ACHqAavVrcDV7:-NC0017B1_Zl89B8eUBq:b-dijz98) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L102)):*
> ```Go
> 	wg.Wait()
> 
> 	assertT.Less(len(mock.calls), 20)
> ```

why 20?


<!-- Sent from Reviewable.io -->

2022-09-15 13:07 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 17 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch.go` line 73 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-50TL1HbkP3ulreMr:-NC0Dt6pEUe5JIK2of_s:b-oijpqc) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L73)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

When is this context canceled then?
</blockquote></details>

only when the caller of this function cancels the context. It does not happen at the moment in http layer but if this function is reused somewhere else and the caller decides to cancel this context, then it will be respected. 
___
*[`client/coreum/batch.go` line 120 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBzhm-Q9f917cjVuIxV:-NC0EC-m8WCyukeHoLfk:bikrwx1) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But we all had a discussion when we agreed that logger is handled inside ctx. Now you pass logger twice, once in constructor, second time in `ctx` here. 
</blockquote></details>

I added a use of logger start and end of goroutine. but I don't need a ctx there. should we pass context there just to have logger ?
___
*[`client/coreum/batch.go` line 135 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-xpUKADf83KgOrZGY:-NC0EwxqEnYRozT08jzX:b2td21c) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch.go#L135)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Non-blocking: this reinvents a framework which logs startup and exit of every goroutine in the app in consistent way. Now you have goroutines which log it and others which don't. Why is this one special? Two suggestions:
- be consistent and log it everywhere then
- let's use a framework which does not require everyone to even think about repeatable tasks
</blockquote></details>

let's do it outside this PR and not block PRs to solve a generic problem. 
___
*[`client/coreum/batch.go` line 144 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-yaz420BFJwOYIEdp:-NC0F4Cd6J-z5VaWD0DV:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch.go#L144)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Do it inside `defer` at the beginning so it is logged even if code panics. Or even create a special case with `recover` logging the panic (reinventing the wheel again)
</blockquote></details>

Done.
___
*[`client/coreum/batch_test.go` line 32 at r4](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBv_hkn5gQZGPqQG8Bv:-NC06YLe2IYmM8PtCgzY:b-h2q5ec) ([raw file](https://github.com/coreumfoundation/faucet/blob/db603e1c5d578abb8bc6cd3a98def35c83f7fc3b/client/coreum/batch_test.go#L32)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

My comment was about the fact that you don't need a goroutine at all
</blockquote></details>

anyways, removed that test
___
*[`client/coreum/batch_test.go` line 15 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC011CGBBV-JjfcIjne:-NC06DiS6A6KZqLAdxkf:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L15)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

It seems to me that the second test tests everything end-to-end so maybe this one is not needed
</blockquote></details>

Done.
___
*[`client/coreum/batch_test.go` line 19 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-zbTnCv3yaAwotiel:-NC060W54nTwIbr63cPU:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L19)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`t.Cleanup(cancel)`
</blockquote></details>

Done.
___
*[`client/coreum/batch_test.go` line 34 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-zEz2Aa37v6UY3Wv2:-NC06SLf0bvnpv28i9zS:bvfshin) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L34)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

return an error in this case because it means that code didn't work as expected, because all the 10 requests should be placed inside buffer immediately
</blockquote></details>

removed this test
___
*[`client/coreum/batch_test.go` line 52 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0-b4l5zfU4Ug_a2dX:-NC0CbzE-Q0BAzSZcyUg:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L52)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

This must be protected by mutex
</blockquote></details>

Done.
___
*[`client/coreum/batch_test.go` line 79 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-zXdq4jjnOYqGDHSy:-NC0CcpJ3U0YgBu5Ye-b:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L79)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

`t.Cleanup(cancel)`
</blockquote></details>

Done.
___
*[`client/coreum/batch_test.go` line 88 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-zslr2lvSXY8ikMFq:-NC0Cebe6ebD7Vysh93d:b-nmv1z6) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L88)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why `*`?
</blockquote></details>

auto completed by IDE. removed. 
___
*[`client/coreum/batch_test.go` line 95 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC00k_aDYzEASvfhdD4:-NC0D7hN5qASU-GlHYg2:b-87hn55) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L95)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Responses should be collected and verified
</blockquote></details>

this is using a mock implementation all responses are empty string, However it makes sense to assert that no error occured. 
___
*[`client/coreum/batch_test.go` line 102 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0017ACHqAavVrcDV7:-NC0DU8p1UYS58XpWaHQ:b-cy8qyt) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L102)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

why 20?
</blockquote></details>

the number of batches is not determnistic, it is between 11 and 13.
20 is a reasonably high number to make sure that requests are getting sent is batches.


<!-- Sent from Reviewable.io -->

2022-09-15 13:19 UTC, wojtek-coreum requested changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`client/coreum/batch.go` line 73 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-50TL1HbkP3ulreMr:-NC0I6mABKxC3kj1aLOy:bf6qo8z) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L73)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

only when the caller of this function cancels the context. It does not happen at the moment in http layer but if this function is reused somewhere else and the caller decides to cancel this context, then it will be respected. 
</blockquote></details>

But originally this ctx comes from `ctx.Request().Context()`. I guess there are two situations when this ctx is cancelled:
- network connection broke (less interesting)
- http server shutdowns - which is super interesting because in this situation batcher should continue. Is it the case?
___
*[`client/coreum/batch.go` line 120 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBzhm-Q9f917cjVuIxV:-NC0GFA8DCm8eiQ7zOCC:b-1x5r13) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L120)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I added a use of logger start and end of goroutine. but I don't need a ctx there. should we pass context there just to have logger ?
</blockquote></details>

you may pass only a logger, just fetch it from `ctx` here
___
*[`client/coreum/batch.go` line 135 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-xpUKADf83KgOrZGY:-NC0GVihE_fkiSIAYhMK:bcfk4y3) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch.go#L135)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

let's do it outside this PR and not block PRs to solve a generic problem. 
</blockquote></details>

then maybe remove this logging from this PR
___
*[`client/coreum/batch.go` line 136 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0GbvhDjUgFg-jC8my:-NC0Gbvi7xUyMO9wshUH:b-d0i294) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/client/coreum/batch.go#L136)):*
> ```Go
> func (b *Batcher) processBatches(fromAddress sdk.AccAddress) {
> 	b.logger.Debug("processBatches started", zap.Stringer("fromAddress", fromAddress))
> 	defer func() {
> ```

ju don't need `func()` wrapper
___
*[`client/coreum/batch_test.go` line 95 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC00k_aDYzEASvfhdD4:-NC0HAwTDlJufxhbJkU6:b8dm5ql) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L95)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this is using a mock implementation all responses are empty string, However it makes sense to assert that no error occured. 
</blockquote></details>

But still batcher should put an imaginary txHash into resp channel, right?
___
*[`client/coreum/batch_test.go` line 67 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0HRxHAvjAJdVmmZVY:-NC0HRxHAvjAJdVmmZVZ:bsyit6k) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/client/coreum/batch_test.go#L67)):*
> ```Go
> 	}
> 
> 	wg.Wait()
> ```

If one of goroutines panic for whatever reason, this will hang


<!-- Sent from Reviewable.io -->

2022-09-15 13:21 UTC, wojtek-coreum reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`client/coreum/batch_test.go` line 67 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0HRxHAvjAJdVmmZVY:-NC0IfxmCWTXVeOMT7DS:b-t40tx1) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/client/coreum/batch_test.go#L67)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

If one of goroutines panic for whatever reason, this will hang
</blockquote></details>

or wait, panic will cause the exit from entire `go test` so it doesn't matter


<!-- Sent from Reviewable.io -->

2022-09-16 08:42 UTC, dzmitryhil reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`client/coreum/batch.go` line 150 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpppZJBFK_RA2lgEEt:-NC4R5MH-dXTFN-B31GH:b4qjvzz) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L150)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We decided to support graceful shutdown to be nice to the users. Then retrying on network hiccups is even more important because they will happen more often than faucet restarts.
</blockquote></details>

I'm ok, to go without the retries here. 
In the future as a common practice we might go with it, but not here, since we can make up a million enhancements for that PR, and it won't be closed ever :-)
Also I didn't get the relationships of the graceful shutdown and retires. The graceful shutdown stops the logic execution gracefully, no matter with the retries or without, since retries are just a part of the logic.


<!-- Sent from Reviewable.io -->

2022-09-16 08:43 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 6 of 10 files reviewed, 8 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch.go` line 73 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-50TL1HbkP3ulreMr:-NC0WFM-3lcJQRM019JP:b-1ojujp) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L73)):*
> ctx.Request().Context()
does not get cancelled on gracefull shutdown. 
___
*[`client/coreum/batch.go` line 120 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBzhm-Q9f917cjVuIxV:-NC4Q6lE9bsIikE7cmn1:brpse9f) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L120)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

you may pass only a logger, just fetch it from `ctx` here
</blockquote></details>

I passed ctx
___
*[`client/coreum/batch.go` line 136 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0GbvhDjUgFg-jC8my:-NC4QBil83kuDU1-zZb3:b-hfpv0l) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/client/coreum/batch.go#L136)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

ju don't need `func()` wrapper
</blockquote></details>

removed
___
*[`client/coreum/batch_test.go` line 95 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC00k_aDYzEASvfhdD4:-NC4QXmf8p86eSeg3StZ:b-zhb4ur) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L95)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

But still batcher should put an imaginary txHash into resp channel, right?
</blockquote></details>

I don't think it is beneficial in anyway, as long as error is checked, we are good.
___
*[`client/coreum/batch_test.go` line 59 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0IvN-0ktWK2v33Cxq:-NC4QfYC9b-CxDg5DJSg:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/client/coreum/batch_test.go#L59)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

You may do `Add(100)` before loop
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-16 09:00 UTC, wojtek-coreum requested changes
> Reviewed 3 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`client/coreum/batch.go` line 150 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpppZJBFK_RA2lgEEt:-NC4WKbCBS03pIun-CSR:b49ouxk) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L150)):*
> Also I didn't get the relationships of the graceful shutdown and retires

The raltionship does not exist, both are separate events:
- graceful shutdown - in case of faucet termination
- retries - in case of tmp network failures

tmp network failures will happen more often than faucet restarts so I don't understand why we implement graceful shutdown because we want to make our users happy, but at the same time we don't provide retries making our users unhappy more often.
___
*[`client/coreum/batch_test.go` line 95 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC00k_aDYzEASvfhdD4:-NC4VrPE3TnMIblXE741:blii7dl) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L95)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I don't think it is beneficial in anyway, as long as error is checked, we are good.
</blockquote></details>

how do you know that result is delivered back to http request then?


<!-- Sent from Reviewable.io -->

2022-09-16 11:07 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 8 of 10 files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch_test.go` line 95 at r8](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC00k_aDYzEASvfhdD4:-NC4X-GH6OLXFL3rI4l6:bngyisd) ([raw file](https://github.com/coreumfoundation/faucet/blob/6922e50f81cca80677e47d47c3d5a60c34372a4f/client/coreum/batch_test.go#L95)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

how do you know that result is delivered back to http request then?
</blockquote></details>

it is a simple var passing, easily verifiable by looking at the code, it is also being checked in the integration test. But there is no harm in doing it here as well.
Added


<!-- Sent from Reviewable.io -->

2022-09-16 11:15 UTC, ysv requested changes
I didn't get this comment. Do you want me to rename it ?
I still see old title 

I suggest smth like:
`Implement batcher to group multiple bank send messages into a single tx`

> Reviewed 1 of 8 files at r1, 1 of 4 files at r2, 2 of 5 files at r3, 1 of 3 files at r7, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11#-:-NC0GlKODVBKBkPnxieL:b-2wcjf4)* status: 8 of 10 files reviewed, 12 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBvLlvp7A_V4tacO7VS:-NC0HKgz9hGihrhCoHGY:bqgfsyg) (no related file):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

If you test it locally, it's had to face such issue. I prefer to have graceful shutdown rather exit.
</blockquote></details>

as we agreed yesterday on the call current shutdown is ok for this app

___
___
*[`Dockerfile` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0HVKz5pk1RveBqZWm:-NC0HVKz5pk1RveBqZWn:b-qzm7f9) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/Dockerfile#L29)):*
> ```Dockerfile
> WORKDIR /
> 
> VOLUME /data/private_keys_mnemonic.txt
> ```

`private_keys_mnemonic.txt` I'm not sure that it is right name for this file
because private key is one thing & mnemonic is completely different.

Should it be just `mnemonics.txt` ?
___
*[`main.go` line 167 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBWifMi6yLOsqfeaceV:-NC0I3Kd6bPYrabGD4w7:b-q1me0u) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/main.go#L167)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it is simpler to put list of mnemonics in a file, if we are to import them via flags, and let's say we have 10 faucet accounts, the command line would be too large
</blockquote></details>

expected, makes sense
___
*[`main.go` line 185 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0KQPp7d3Yrs4O4_8P:-NC0KQPp7d3Yrs4O4_8Q:b3yogek) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/main.go#L185)):*
> ```Go
> 	var addresses []sdk.AccAddress
> 	for scanner.Scan() {
> 		mnemonic := scanner.Text()
> ```

 mnemonics are separated by newline, aren't they ?
___
*[`main.go` line 193 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0IGJi3ugX7U2JfC6p:-NC0IGJi3ugX7U2JfC6q:b-6fzhl0) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/main.go#L193)):*
> ```Go
> 		address := info.GetAddress()
> 		addresses = append(addresses, address)
> 		_, _ = kr.NewAccount(address.String(), mnemonic, "", "", hd.Secp256k1)
> ```

do not ignore err here
___
*[`main.go` line 197 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0Kf7hAtiYJr2-U5IF:-NC0Kf7hAtiYJr2-U5IG:b4grdy2) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/main.go#L197)):*
> ```Go
> 
> 	if len(addresses) == 0 {
> 		return nil, nil, errors.New("could not parse any funding private keys")
> ```

any mnemonic ?
___
*[`app/app.go` line 30 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX43Ba8KXpwV9q7Goe:-NC0Kqpo3oikLkEAOdvr:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/app/app.go#L30)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

refactored the code and it now needs it. IMO start is just internals of the batcher and should not be exposed to the outside world
</blockquote></details>

ok
___
*[`app/app.go` line 33 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0NiQn7x3ckr5XGopv:-NC0NiQn7x3ckr5XGopw:b-u5fpep) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/app/app.go#L33)):*
> ```Go
> 
> // CoreumClient indicates the required functionality to connect to coreum blockchain
> type CoreumClient interface {
> ```

not the best name for this interface:
1. we have client which is really client while this one isn't
2. It is implemented by batcher which is strange
___
*[`app/app.go` line 34 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0NG-P9Y_Sw33vXZPt:-NC0NG-P9Y_Sw33vXZPu:bib1eb0) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/app/app.go#L34)):*
> ```Go
> // CoreumClient indicates the required functionality to connect to coreum blockchain
> type CoreumClient interface {
> 	TransferToken(ctx context.Context, destAddress sdk.AccAddress) (string, error)
> ```

I don't like this name because it conflicts with the same name in `(c Client) TransferToken` but signature and meaning is very different
___
*[`client/coreum/batch.go` line 150 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpppZJBFK_RA2lgEEt:-NC0QVPa-P2yCZO7Ulkt:bkddjzj) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L150)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

We decided to support graceful shutdown to be nice to the users. Then retrying on network hiccups is even more important because they will happen more often than faucet restarts.
</blockquote></details>

retrials are nice to have probably but not in this PR
TODO is welcome
___
*[`client/coreum/batch.go` line 1 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0PDv09gtJCxmllRQu:-NC0PDv09gtJCxmllRQv:b-mx2zwz) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/client/coreum/batch.go#L1)):*
> ```Go
> package coreum
> ```

rename file to batcher.go
___
*[`client/coreum/client.go` line 45 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0QxxiAfjSKV4udZji:-NC0QxxiAfjSKV4udZjj:bpzfmtw) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/client/coreum/client.go#L45)):*
> ```Go
> 	ctx context.Context,
> 	fromAddress sdk.AccAddress,
> 	amount sdk.Coin,
> ```

non-blocking:
I think that having amount+destAddress as slice of struct is more flexible because
```
func TranferToken(ctx, fromAddres, []struct
```



<!-- Sent from Reviewable.io -->

2022-09-16 13:10 UTC, wojtek-coreum reviewed
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`client/coreum/batch.go` line 73 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-50TL1HbkP3ulreMr:-NC4WtrO2Pbl21SU-Z6a:bmmhymf) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L73)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

> ctx.Request().Context()
does not get cancelled on gracefull shutdown. 
</blockquote></details>

Is it like this because of our implementation of  http server or it's an internal decision of echo? It seems to be weird because let's say then is an ongoing websocket communication. How does it know that it should be terminated?


<!-- Sent from Reviewable.io -->

2022-09-16 15:02 UTC, miladz68 reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11#-:-NC5bSgUBnzmC6JcG5qf:bb6un1j)* status: all files reviewed, 11 unresolved discussions (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

___
*[`Dockerfile` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0HVKz5pk1RveBqZWm:-NC5m706D1KY9qhGCCdT:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/Dockerfile#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

`private_keys_mnemonic.txt` I'm not sure that it is right name for this file
because private key is one thing & mnemonic is completely different.

Should it be just `mnemonics.txt` ?
</blockquote></details>

Done.
___
*[`main.go` line 185 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0KQPp7d3Yrs4O4_8P:-NC5a7ZZ5plGDiwhxD-3:b-gcjli7) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/main.go#L185)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

 mnemonics are separated by newline, aren't they ?
</blockquote></details>

they are
___
*[`main.go` line 193 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0IGJi3ugX7U2JfC6p:-NC5nsqd1sjkVzk2mO5F:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/main.go#L193)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do not ignore err here
</blockquote></details>

Done.
___
*[`main.go` line 197 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0Kf7hAtiYJr2-U5IF:-NC5dJMC2f2dB0HahRs0:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/main.go#L197)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

any mnemonic ?
</blockquote></details>

Done.
___
*[`app/app.go` line 33 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0NiQn7x3ckr5XGopv:-NC5mHeC7cZLTanWsGkX:bw9idni) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/app/app.go#L33)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

not the best name for this interface:
1. we have client which is really client while this one isn't
2. It is implemented by batcher which is strange
</blockquote></details>

I will remove the client word and just keep coreum. this interface defines the functionality required to communicate with coreum block chain. 
___
*[`app/app.go` line 34 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0NG-P9Y_Sw33vXZPt:-NC5mttE6R2GI2oRAAUk:b-5iluq5) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/app/app.go#L34)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't like this name because it conflicts with the same name in `(c Client) TransferToken` but signature and meaning is very different
</blockquote></details>

I will rename it to SendToken to distinquish the 2 of them. 
___
*[`client/coreum/batch.go` line 150 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpppZJBFK_RA2lgEEt:-NC5o5gO94-osFSRQStH:b-hukn99) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L150)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

retrials are nice to have probably but not in this PR
TODO is welcome
</blockquote></details>

Added TODO.
___
*[`client/coreum/batch.go` line 73 at r5](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC-50TL1HbkP3ulreMr:-NC5nBh_3SKSwFSO3iWm:b-vh229i) ([raw file](https://github.com/coreumfoundation/faucet/blob/426fdd08a4b051aa703a12aa87568eb4105f966e/client/coreum/batch.go#L73)):*
<details><summary><i>Previously, wojtek-coreum (Wojtek) wrote…</i></summary><blockquote>

Is it like this because of our implementation of  http server or it's an internal decision of echo? It seems to be weird because let's say then is an ongoing websocket communication. How does it know that it should be terminated?
</blockquote></details>

It is how it is done by the default http.Shutdown method on standard library. 
Regarding websockets, it is dependent on the implementation of the websocket, if websocket wants to terminate this function it just needs to cancel the context, otherwise the websocket can wait for it to finish and do proper graceful shutdown. 
___
*[`client/coreum/batch.go` line 1 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0PDv09gtJCxmllRQu:-NC5dQg49KEift1Q8zvI:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/client/coreum/batch.go#L1)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

rename file to batcher.go
</blockquote></details>

Done.
___
*[`client/coreum/client.go` line 45 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0QxxiAfjSKV4udZji:-NC5lpTi2TRX6lus6cbG:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/client/coreum/client.go#L45)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

non-blocking:
I think that having amount+destAddress as slice of struct is more flexible because
```
func TranferToken(ctx, fromAddres, []struct
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-19 16:32 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 5 of 10 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`Dockerfile` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0HVKz5pk1RveBqZWm:-NCLYzjvAX3fV7HKeWLI:bdgdh77) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/Dockerfile#L29)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

still see version without update
___
*[`main.go` line 185 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0KQPp7d3Yrs4O4_8P:-NCLY4UlCZm6tKfzXhiS:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/main.go#L185)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

they are
</blockquote></details>

ok
___
*[`main.go` line 193 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0IGJi3ugX7U2JfC6p:-NCLY6Vr1gY5fj6jxIaJ:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/main.go#L193)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok
___
*[`main.go` line 197 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0Kf7hAtiYJr2-U5IF:-NCLY83s0ws54fx7dSTh:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/main.go#L197)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok
___
*[`app/app.go` line 33 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0NiQn7x3ckr5XGopv:-NCL_5s_7QR-XhznCgtH:b-jitzy9) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/app/app.go#L33)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I will remove the client word and just keep coreum. this interface defines the functionality required to communicate with coreum block chain. 
</blockquote></details>

still don't like it much
What about `TokenBatcher` or `Batcher`

App has TokenBatcher which is responsible for sending tokens
I think it is logical
___
*[`app/app.go` line 34 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0NG-P9Y_Sw33vXZPt:-NCLYFy6AG9nk4XMSj_L:b-l2j9x7) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/app/app.go#L34)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I will rename it to SendToken to distinquish the 2 of them. 
</blockquote></details>

ok, better
___
*[`client/coreum/batch.go` line 41 at r1](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBX4KFZ9kbLQ9tTj9lD:-NCLYXXo6Jalinr9EHT3:b-zf613y) ([raw file](https://github.com/coreumfoundation/faucet/blob/0c7a6d8d23ec01be4e0b28398cb5109784bbf9fb/client/coreum/batch.go#L41)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

it is more accurately coreumClient. cored is the binary and coreum is the blockchain, this is client of the blockchain. 
</blockquote></details>

I see
I'm always confused by cored vs coreum naming 
will discuss with the team
___
*[`client/coreum/batch.go` line 150 at r2](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NBpppZJBFK_RA2lgEEt:-NCL_d6BBOUCmgaQzJVJ:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/64d6d2293c29db83b61835a725fef46e49c39f41/client/coreum/batch.go#L150)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Added TODO.
</blockquote></details>

ok
___
*[`client/coreum/batch.go` line 1 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0PDv09gtJCxmllRQu:-NCLYMsHBMxScCQrC9ht:b2ni9ah) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/client/coreum/batch.go#L1)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-09-20 06:44 UTC, wojtek-coreum submitted a review, later dismissed
> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)



<!-- Sent from Reviewable.io -->

2022-09-20 12:38 UTC, dzmitryhil submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 2 unresolved discussions (waiting on @miladz68 and @ysv)



<!-- Sent from Reviewable.io -->

2022-09-21 05:04 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 2 unresolved discussions (waiting on @ysv)

___
*[`Dockerfile` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0HVKz5pk1RveBqZWm:-NCTQMuo0_quc5vJoTan:b-bu91xm) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/Dockerfile#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

still see version without update
</blockquote></details>

Updated
___
*[`app/app.go` line 33 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0NiQn7x3ckr5XGopv:-NCTQ8OoE25jwXgQQNwq:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/app/app.go#L33)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

still don't like it much
What about `TokenBatcher` or `Batcher`

App has TokenBatcher which is responsible for sending tokens
I think it is logical
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-21 07:51 UTC, wojtek-coreum submitted a review, later dismissed
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: all files reviewed, 2 unresolved discussions (waiting on @ysv)



<!-- Sent from Reviewable.io -->

2022-09-21 10:50 UTC, ysv requested changes
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @miladz68, @wojtek-coreum, and @ysv)

___
*[`Dockerfile` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0HVKz5pk1RveBqZWm:-NCUe_sC2Opky_B5OTOl:baeft1r) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/Dockerfile#L29)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Updated
</blockquote></details>

1. pls make sure to let Artem know about changes required on his side
2. update README as far as I remember this file was mentioned there
___
*[`app/app.go` line 33 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0NiQn7x3ckr5XGopv:-NCUeuL82fTFoeZoeTsL:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/app/app.go#L33)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-09-21 10:56 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @wojtek-coreum and @ysv)

___
*[`Dockerfile` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0HVKz5pk1RveBqZWm:-NCUgBFE6Qqd13RAOgPK:b-896fix) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/Dockerfile#L29)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

1. pls make sure to let Artem know about changes required on his side
2. update README as far as I remember this file was mentioned there
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-21 11:02 UTC, ysv submitted a review, later dismissed
> Reviewed 1 of 8 files at r1, 4 of 5 files at r13, 2 of 2 files at r14, 2 of 2 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wojtek-coreum)

___
*[`Dockerfile` line 29 at r9](https://reviewable.io/reviews/coreumfoundation/faucet/11#-NC0HVKz5pk1RveBqZWm:-NCUgpWV5tP8ng13u9t7:b32wtd) ([raw file](https://github.com/coreumfoundation/faucet/blob/9448d70e7a0ad3e688ea5c69d41653203242f60c/Dockerfile#L29)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-09-21 12:46 UTC, wojtek-coreum approved these changes
> Reviewed 2 of 2 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)



<!-- Sent from Reviewable.io -->

2022-09-21 13:36 UTC, ysv approved these changes
> Reviewed 1 of 1 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)



<!-- Sent from Reviewable.io -->

2022-09-21 13:40 UTC, wojtek-coreum approved these changes
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/faucet/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @miladz68)



<!-- Sent from Reviewable.io -->

2022-09-21 14:03 UTC, merged